# NeoOLAF native EventStoryLine layer ablation — one document v1.3

This v1.3 notebook keeps the same **OWL-Time** ontology used in RAGTree and the controlled labels `PRECONDITION`/`FALLING_ACTION`. Layer 1 now uses parallel sentence-level event inventories, two whole-document coverage reviews, and source-batched closed-inventory PLOT_LINK generation. Gold remains unavailable until after Layer 12.

In [1]:
from __future__ import annotations

import os
import sys
from getpass import getpass
from pathlib import Path

import pandas as pd
from IPython.display import display, Markdown


def find_project_root() -> Path:
    current = Path.cwd().resolve()
    for candidate in [current, *current.parents]:
        if (candidate / "pyproject.toml").is_file() and (candidate / "src/neoolaf").is_dir():
            return candidate
    raise FileNotFoundError("Run this notebook from inside the NeoOLAF repository.")


def first_existing_path(env_name: str, candidates: list[Path]) -> Path:
    raw = os.environ.get(env_name, "").strip().strip('"').strip("'")
    if raw:
        path = Path(raw).expanduser().resolve()
        if path.is_file():
            return path
        raise FileNotFoundError(f"{env_name} points to a missing file: {path}")
    for candidate in candidates:
        candidate = candidate.expanduser().resolve()
        if candidate.is_file():
            return candidate
    raise FileNotFoundError(
        f"Could not find {env_name}. Tried:\n"
        + "\n".join(str(Path(x).expanduser().resolve()) for x in candidates)
    )


PROJECT_ROOT = find_project_root()
NOTEBOOK_DIR = PROJECT_ROOT / "examples/RAGTreeDatasets"
TOOLS_DIR = NOTEBOOK_DIR / "tools"
for path in [PROJECT_ROOT / "src", PROJECT_ROOT, TOOLS_DIR]:
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from eventstoryline_native_ablation_v1_3 import (
    RELATION_IDS,
    analyze_run,
    gold_event_index,
    indexed_token_table,
    load_layer_states,
    project_event_label,
    read_json,
    read_jsonl,
    run_native_pipeline,
    seed_ontology_summary,
)

print("PROJECT_ROOT =", PROJECT_ROOT)

PROJECT_ROOT = /home/galencarmedeiro/git/postdoc/NeoOLAF

/home/galencarmedeiro/git/postdoc/NeoOLAF/.venv/lib/python3.12/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.2.0)/charset_normalizer (3.4.6) doesn't match a supported version!
  warnings.warn(
/home/galencarmedeiro/git/postdoc/NeoOLAF/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Configuration

In [2]:
INPUT_JSONL = NOTEBOOK_DIR / "data/eventstoryline_one_input_v1.jsonl"
GOLD_JSONL = NOTEBOOK_DIR / "data/eventstoryline_one_gold_v1.jsonl"
SMOKE5_INPUT_JSONL = NOTEBOOK_DIR / "data/eventstoryline_smoke5_input_v1.jsonl"
SMOKE5_GOLD_JSONL = NOTEBOOK_DIR / "data/eventstoryline_smoke5_gold_v1.jsonl"

# Same seed ontology used by the RAGTree EventStoryLine experiments.
# Override explicitly with EVENTSTORYLINE_ONTOLOGY_PATH when needed.
ONTOLOGY_PATH = first_existing_path(
    "EVENTSTORYLINE_ONTOLOGY_PATH",
    [
        PROJECT_ROOT.parent / "ragtree/data/ontology/OWLTime/time.ttl",
        PROJECT_ROOT.parent / "RAGTree/data/ontology/OWLTime/time.ttl",
        PROJECT_ROOT / "../ragtree/data/ontology/OWLTime/time.ttl",
        PROJECT_ROOT / "../RAGTree/data/ontology/OWLTime/time.ttl",
    ],
)

# Controlled normalized benchmark relation schema. This is not the seed ontology.
RELATION_CATALOG = NOTEBOOK_DIR / "ontology/eventstoryline_relation_catalog.json"
RELATION_ALIASES = NOTEBOOK_DIR / "ontology/eventstoryline_relation_aliases.json"
PROFILE_PATH = NOTEBOOK_DIR / "configs/eventstoryline_profile_native_ablation_v1_3.json"
GUIDANCE_PATH = NOTEBOOK_DIR / "configs/guidance_eventstoryline_native_ablation_v1_3.json"
TASK_GUIDANCE_PATH = NOTEBOOK_DIR / "configs/eventstoryline_task_guidance_v1_3.json"

RUNS_ROOT = NOTEBOOK_DIR / "runs/eventstoryline_native_layer_ablation"
RUN_DIR = RUNS_ROOT / "document_1_10ecbplus_v1_3_owltime_recall"

OPENROUTER_HOST = "https://openrouter.ai/api/v1"
MODEL_NAME = "openai/gpt-oss-20b"
API_KEY = os.environ.get("OPENROUTER_API_KEY", "").strip().strip('"').strip("'")

# Relation-instance decisions are independent and run concurrently in Layer 2.
WORKERS = 16
REASONING_EFFORT = "minimal"
RUN_PIPELINE = True
CLEAN_RUN_DIR = True

print("Input:", INPUT_JSONL)
print("Gold:", GOLD_JSONL)
print("OWL-Time seed ontology:", ONTOLOGY_PATH)
print("Controlled relation catalog:", RELATION_CATALOG)
print("Profile:", PROFILE_PATH)
print("Guidance:", GUIDANCE_PATH)
print("Task guidance:", TASK_GUIDANCE_PATH)
print("Run dir:", RUN_DIR)
print("Model:", MODEL_NAME)
print("API key available:", bool(API_KEY))

Input: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/data/eventstoryline_one_input_v1.jsonl
Gold: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/data/eventstoryline_one_gold_v1.jsonl
OWL-Time seed ontology: /home/galencarmedeiro/git/postdoc/ragtree/data/ontology/OWLTime/time.ttl
Controlled relation catalog: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/ontology/eventstoryline_relation_catalog.json
Profile: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/configs/eventstoryline_profile_native_ablation_v1_3.json
Guidance: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/configs/guidance_eventstoryline_native_ablation_v1_3.json
Task guidance: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/configs/eventstoryline_task_guidance_v1_3.json
Run dir: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/runs/eventstoryline_native_layer_ablation/document_1_10ecbplus_v1_3_owltime_recall
Model: openai/gpt-oss-20b
API key available: True

## 2. Preflight: anti-leakage, OWL-Time seed ontology, five-document files and event identity

In [3]:
required = [
    INPUT_JSONL, GOLD_JSONL, SMOKE5_INPUT_JSONL, SMOKE5_GOLD_JSONL,
    ONTOLOGY_PATH, RELATION_CATALOG, RELATION_ALIASES,
    PROFILE_PATH, GUIDANCE_PATH, TASK_GUIDANCE_PATH,
]
missing = [str(path) for path in required if not path.is_file()]
if missing:
    raise FileNotFoundError("Missing required files:\n" + "\n".join(missing))

input_rows = read_jsonl(INPUT_JSONL)
gold_rows = read_jsonl(GOLD_JSONL)
smoke_input_rows = read_jsonl(SMOKE5_INPUT_JSONL)
smoke_gold_rows = read_jsonl(SMOKE5_GOLD_JSONL)
assert len(input_rows) == 1 and len(gold_rows) == 1
assert len(smoke_input_rows) == 5 and len(smoke_gold_rows) == 5
assert "entities" not in input_rows[0] and "relations" not in input_rows[0]
assert all("entities" not in row and "relations" not in row for row in smoke_input_rows)
assert input_rows[0]["document_id"] == gold_rows[0]["document_id"]
assert [x["document_id"] for x in smoke_input_rows] == [x["document_id"] for x in smoke_gold_rows]

profile = read_json(PROFILE_PATH)
task = read_json(TASK_GUIDANCE_PATH)
catalog = read_json(RELATION_CATALOG)
gold = gold_rows[0]
seed_summary = seed_ontology_summary(ONTOLOGY_PATH)

print("Document:", input_rows[0]["document_id"], "-", input_rows[0]["title"])
print("Source characters:", len(input_rows[0]["text"]))
print("Sentences:", len(input_rows[0]["sentences"]))
print("Source tokens:", sum(len(x) for x in input_rows[0]["tokens"]))
print("Gold events (not exposed to pipeline):", len(gold["entities"]))
print("Gold evaluated relations:", sum(len(v) for k, v in gold["relations"].items() if k in RELATION_IDS))
print("Ignored null pairs:", len(gold["relations"].get("null", [])))
print("OWL-Time classes loaded:", seed_summary["class_count"])
print("OWL-Time properties loaded:", seed_summary["property_count"])
print("Controlled task relations:", catalog["property_count"])
print("Relation IDs:", task["allowed_relation_ids"])
print("Layer 1 sentence workers:", profile["layers"]["layer01_linguistic_expression_extraction"]["sentence_workers"])
print("Layer 1 coverage reviews:", profile["layers"]["layer01_linguistic_expression_extraction"]["coverage_review_passes"])
print("Layer 1 relation workers:", profile["layers"]["layer01_linguistic_expression_extraction"]["relation_workers"])
print("Layer 1 source batch size:", profile["layers"]["layer01_linguistic_expression_extraction"]["relation_source_batch_size"])
print("Layer 2 workers:", profile["layers"]["layer02_candidate_enrichment"]["max_concurrency"])
print("Mention-free relation schemas injected:", len(profile["relations"]["allowed"]))
print("Five-document input IDs:", [row["document_id"] for row in smoke_input_rows])

assert seed_summary["class_count"] > 0 or seed_summary["property_count"] > 0
assert catalog["property_count"] == 2
assert set(task["allowed_relation_ids"]) == set(RELATION_IDS)
assert profile["relations"]["allowed"] == []
assert profile["anti_cheating"]["direct_eventstoryline_extraction"] is False
assert profile["anti_cheating"]["source_event_anchoring"] is False
assert profile["anti_cheating"]["gold_pair_hints"] is False
assert profile["anti_cheating"]["post_run_relation_invention"] is False
assert profile["benchmark_projection"]["gold_available_to_pipeline"] is False
assert profile["benchmark_projection"]["same_seed_ontology_as_ragtree"] is True

display(Markdown("### Indexed source table used by Layer 1"))
print(indexed_token_table(input_rows[0]["sentences"], input_rows[0]["tokens"]))

assert profile["anti_cheating"]["gold_event_lexicon"] is False
assert profile["anti_cheating"]["gold_event_count"] is False
assert profile["anti_cheating"]["gold_relation_count"] is False

Document: EventStoryLine - 1_10ecbplus - 1_10ecbplus
Source characters: 745
Sentences: 6
Source tokens: 147
Gold events (not exposed to pipeline): 15
Gold evaluated relations: 20
Ignored null pairs: 1
OWL-Time classes loaded: 23
OWL-Time properties loaded: 62
Controlled task relations: 2
Relation IDs: ['PRECONDITION', 'FALLING_ACTION']
Layer 1 sentence workers: 8
Layer 1 coverage reviews: 2
Layer 1 relation workers: 8
Layer 1 source batch size: 4
Layer 2 workers: 16
Mention-free relation schemas injected: 0
Five-document input IDs: ['EventStoryLine - 1_10ecbplus', 'EventStoryLine - 1_11ecbplus', 'EventStoryLine - 1_12ecbplus', 'EventStoryLine - 1_13ecbplus', 'EventStoryLine - 1_14ecbplus']

### Indexed source table used by Layer 1

[S0] http : / / articles . latimes . com / 2013 / may / 03 / local / la - me - 0504 - lohan - rehab - 20130504
TOKENS 0=http 1=: 2=/ 3=/ 4=articles 5=. 6=latimes 7=. 8=com 9=/ 10=2013 11=/ 12=may 13=/ 14=03 15=/ 16=local 17=/ 18=la 19=- 20=me 21=- 22=0504 23=- 24=lohan 25=- 26=rehab 27=- 28=20130504

[S1] Lindsay Lohan checks into Betty Ford Center
TOKENS 0=Lindsay 1=Lohan 2=checks 3=into 4=Betty 5=Ford 6=Center

[S2] May 03 , 2013
TOKENS 0=May 1=03 2=, 3=2013

[S3] After skipping out on entering a Newport Beach rehabilitation facility and facing the prospect of arrest for violating her probation , Lindsay Lohan has checked into the Betty Ford Center to begin a 90 - day court - mandated stay in her reckless driving conviction .
TOKENS 0=After 1=skipping 2=out 3=on 4=entering 5=a 6=Newport 7=Beach 8=rehabilitation 9=facility 10=and 11=facing 12=the 13=prospect 14=of 15=arrest 16=for 17=violating 18=her 19=probation 20=, 21=Lindsay 22=Lohan 23=has 24=checked 25=into 26=the 27=Betty 28=Ford 29=Center 30=to 31=begin 32=a 33=90 34=- 35=day 36=court 37=- 38=mandated 39=stay 40=in 41=her 42=reckless 43=driving 44=conviction 45=.

[S4] Lohan was previously at Betty Ford from September 2010 to January 2011 after a probation violation in a prior drunk driving case .
TOKENS 0=Lohan 1=was 2=previously 3=at 4=Betty 5=Ford 6=from 7=September 8=2010 9=to 10=January 11=2011 12=after 13=a 14=probation 15=violation 16=in 17=a 18=prior 19=drunk 20=driving 21=case 22=.

[S5] Her latest stay at Betty Ford comes after Lohan rear - ended a truck with her Porsche on Pacific Coast Highway on June 8 , and then lied to police , telling them she was not driving .
TOKENS 0=Her 1=latest 2=stay 3=at 4=Betty 5=Ford 6=comes 7=after 8=Lohan 9=rear 10=- 11=ended 12=a 13=truck 14=with 15=her 16=Porsche 17=on 18=Pacific 19=Coast 20=Highway 21=on 22=June 23=8 24=, 25=and 26=then 27=lied 28=to 29=police 30=, 31=telling 32=them 33=she 34=was 35=not 36=driving 37=.

## 3. Run the full native Layer 0--12 pipeline

In [4]:
if RUN_PIPELINE:
    if not API_KEY:
        API_KEY = getpass("OpenRouter API key: ").strip().strip('"').strip("'")
    if not API_KEY:
        raise RuntimeError("No OpenRouter API key was provided.")

    final_state = run_native_pipeline(
        project_root=PROJECT_ROOT,
        input_jsonl=INPUT_JSONL,
        ontology_path=ONTOLOGY_PATH,
        profile_path=PROFILE_PATH,
        guidance_path=GUIDANCE_PATH,
        task_guidance_path=TASK_GUIDANCE_PATH,
        relation_catalog_path=RELATION_CATALOG,
        relation_aliases_path=RELATION_ALIASES,
        run_dir=RUN_DIR,
        model_name=MODEL_NAME,
        api_key=API_KEY,
        host=OPENROUTER_HOST,
        workers=WORKERS,
        reasoning_effort=REASONING_EFFORT,
        verbose=True,
        clean_run_dir=CLEAN_RUN_DIR,
    )
    print("Full native run completed.")
else:
    print("RUN_PIPELINE=False: reusing", RUN_DIR)

[NeoOLAF] Run directory: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/runs/eventstoryline_native_layer_ablation/document_1_10ecbplus_v1_3_owltime_recall
[NeoOLAF] from_layer=0, to_layer=12, skip_layers=None
[NeoOLAF] Pipeline has 13 layers
[NeoOLAF] Selected layers: ['layer00_preprocessing', 'layer01_linguistic_expression_extraction', 'layer02_candidate_enrichment', 'layer03_candidate_typing_resolution', 'layer04_candidate_relation_extraction', 'layer05_candidate_triple_generation', 'layer06_concept_relation_induction', 'layer07_hierarchisation', 'layer08_axiom_schemata_extraction', 'layer09_general_axiom_extraction', 'layer10_validation_reasoning', 'layer11_inference_completion', 'layer12_serialization']
[NeoOLAF] Layer 0/12: layer00_preprocessing

[NeoOLAF] Starting layer: layer00_preprocessing
[NeoOLAF] Finished layer: layer00_preprocessing in 0.01s
[NeoOLAF] Layer 1/12: layer01_linguistic_expression_extraction

[NeoOLAF] Starting layer: layer01_linguistic_expression_extraction
[NeoOLAF] Finished layer: layer01_linguistic_expression_extraction in 170.57s
[NeoOLAF] Layer 2/12: layer02_candidate_enrichment

[NeoOLAF] Starting layer: layer02_candidate_enrichment
[NeoOLAF] Finished layer: layer02_candidate_enrichment in 32.69s
[NeoOLAF] Layer 3/12: layer03_candidate_typing_resolution

[NeoOLAF] Starting layer: layer03_candidate_typing_resolution
[NeoOLAF][Layer 3] strategy=ontology_aware_role_based_typing

[NeoOLAF] Finished layer: layer03_candidate_typing_resolution in 0.01s
[NeoOLAF] Layer 4/12: layer04_candidate_relation_extraction

[NeoOLAF] Starting layer: layer04_candidate_relation_extraction
[NeoOLAF][Layer 4] strategy=structured_exact_then_native_parallel_fallback; parallel_workers=8; attempts=1
[NeoOLAF] Finished layer: layer04_candidate_relation_extraction in 0.01s
[NeoOLAF] Layer 5/12: layer05_candidate_triple_generation

[NeoOLAF] Starting layer: layer05_candidate_triple_generation

[NeoOLAF] Finished layer: layer05_candidate_triple_generation in 0.00s
[NeoOLAF] Layer 6/12: layer06_concept_relation_induction

[NeoOLAF] Starting layer: layer06_concept_relation_induction
[NeoOLAF][Layer 6] deterministic ontology-aware concept induction for 18 node candidates; no LLM calls.
[NeoOLAF][Layer 6] deterministic ontology-aware relation induction for 26 relation candidates; no LLM calls.
[NeoOLAF] Finished layer: layer06_concept_relation_induction in 0.00s
[NeoOLAF] Layer 7/12: layer07_hierarchisation

[NeoOLAF] Starting layer: layer07_hierarchisation
[NeoOLAF] Finished layer: layer07_hierarchisation in 0.00s
[NeoOLAF] Layer 8/12: layer08_axiom_schemata_extraction

[NeoOLAF] Starting layer: layer08_axiom_schemata_extraction
[NeoOLAF][Layer 8] strategy=ontology_aware_axiom_schema_generation
[NeoOLAF] Finished layer: layer08_axiom_schemata_extraction in 0.00s
[NeoOLAF] Layer 9/12: layer09_general_axiom_extraction

[NeoOLAF] Starting layer: layer09_general_axiom_extraction
[NeoOLAF][Layer 9] strategy=ontology_aware_schema_to_general_axioms; no LLM calls.
[NeoOLAF] Finished layer: layer09_general_axiom_extraction in 0.00s
[NeoOLAF] Layer 10/12: layer10_validation_reasoning

[NeoOLAF] Starting layer: layer10_validation_reasoning

[NeoOLAF] Finished layer: layer10_validation_reasoning in 0.00s
[NeoOLAF] Layer 11/12: layer11_inference_completion

[NeoOLAF] Starting layer: layer11_inference_completion
[NeoOLAF][Layer 11] strategy=ontology_aware_semantic_completion
[NeoOLAF][Layer 11] deterministic completion; max_concurrency=16; no LLM calls.
[NeoOLAF] Finished layer: layer11_inference_completion in 0.00s
[NeoOLAF] Layer 12/12: layer12_serialization

[NeoOLAF] Starting layer: layer12_serialization
[NeoOLAF] Exports written to: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/runs/eventstoryline_native_layer_ablation/document_1_10ecbplus_v1_3_owltime_recall/exports
[NeoOLAF] Finished layer: layer12_serialization in 0.04s
[NeoOLAF] Pipeline finished in 203.56s
[NeoOLAF] Saved checkpoint: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/runs/eventstoryline_native_layer_ablation/document_1_10ecbplus_v1_3_owltime_recall/checkpoints/after_selected_pipeline.pkl.gz
[NeoOLAF] Total run time: 203.57s
Full native run completed.

### Runtime evidence saved

- `run_manifest.json` records OWL-Time and the v1.3 operational fingerprint.
- `run_logs/layer01_call_audit.json` records sentence calls, coverage reviews, and source batches.
- `run_logs/layer01_event_inventory.json` records every accepted/rejected span proposal.
- `run_logs/layer01_relation_generation.json` records closed-inventory pair proposals.
- `run_logs/layer01_event_relation_instances.json` records materialized expressions.
- Layer 2/4 decisions, ontology retrieval, API responses, and all Layer 0--12 states remain saved.

## 4. Strict event and relation evaluation

In [5]:
summary = analyze_run(
    run_dir=RUN_DIR,
    gold_jsonl=GOLD_JSONL,
    catalog_path=RELATION_CATALOG,
    aliases_path=RELATION_ALIASES,
)

display(pd.DataFrame(summary["layer_summary"]))

print("Strict relation evaluation; null relations excluded")
display(pd.DataFrame([summary["strict_relation_evaluation"]]))

print("Event mention inventory evaluation")
display(pd.DataFrame([summary["event_entity_evaluation"]]))

print("Relation-endpoint event inventory evaluation")
display(pd.DataFrame([summary["relation_endpoint_evaluation"]]))

print("Per-relation metrics")
display(pd.DataFrame(summary["per_relation_metrics"]))

print("Cumulative evaluation")
display(pd.DataFrame(summary["cumulative_evaluation"]))

print("First-failure counts")
print(summary["failure_counts"])

,layer,layer_name,linguistic_expressions,enriched_expressions,entity_candidates,relation_candidates,attribute_candidates,event_candidates,candidate_relation_assertions,candidate_triples,concept_candidates,ontology_relation_candidates,concept_hierarchy_links,relation_hierarchy_links,axiom_schema_candidates,general_axiom_candidates,completion_candidates,validation_issues,reasoning_inferred_triples
0,0,layer00_preprocessing,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,layer01_linguistic_expression_extraction,44,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2,layer02_candidate_enrichment,44,44,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,3,layer03_candidate_typing_resolution,44,44,0,26,0,18,0,0,0,0,0,0,0,0,0,0,0
4,4,layer04_candidate_relation_extraction,44,44,0,26,0,18,26,0,0,0,0,0,0,0,0,0,0
5,5,layer05_candidate_triple_generation,44,44,0,26,0,18,26,26,0,0,0,0,0,0,0,0,0
6,6,layer06_concept_relation_induction,44,44,0,26,0,18,26,26,0,3,0,0,0,0,0,0,0
7,7,layer07_hierarchisation,44,44,0,26,0,18,26,26,0,3,0,3,0,0,0,0,0
8,8,layer08_axiom_schemata_extraction,44,44,0,26,0,18,26,26,0,3,0,3,7,0,0,0,0
9,9,layer09_general_axiom_extraction,44,44,0,26,0,18,26,26,0,3,0,3,7,10,0,0,0
10,10,layer10_validation_reasoning,44,44,0,26,0,18,26,26,0,3,0,3,7,10,0,0,26
11,11,layer11_inference_completion,44,44,0,26,0,18,26,26,0,3,0,3,7,10,0,0,26
12,12,layer12_serialization,44,44,0,26,0,18,26,26,0,3,0,3,7,10,0,0,26

Strict relation evaluation; null relations excluded

,predicted,gold,true_positive,false_positive,false_negative,precision,recall,f1
0,15,20,2,13,18,0.133333,0.1,0.114286

Event mention inventory evaluation

,predicted,gold,true_positive,false_positive,false_negative,precision,recall,f1
0,12,15,12,0,3,1.0,0.8,0.888889

Relation-endpoint event inventory evaluation

,predicted,gold,true_positive,false_positive,false_negative,precision,recall,f1
0,11,14,11,0,3,1.0,0.785714,0.88

Per-relation metrics

,relation_id,predicted,gold,true_positive,false_positive,false_negative,precision,recall,f1
0,PRECONDITION,13,7,2,11,5,0.153846,0.285714,0.2
1,FALLING_ACTION,2,13,0,2,13,0.000000,0.000000,0.0

Cumulative evaluation

,layer,layer_name,relation_predicted,relation_gold,relation_true_positive,relation_false_positive,relation_false_negative,relation_precision,relation_recall,relation_f1,event_predicted,event_gold,event_true_positive,event_false_positive,event_false_negative,event_precision,event_recall,event_f1
0,0,layer00_preprocessing,0,20,0,0,20,0.000000,0.0,0.000000,0,15,0,0,15,0.0,0.0,0.000000
1,1,layer01_linguistic_expression_extraction,0,20,0,0,20,0.000000,0.0,0.000000,12,15,12,0,3,1.0,0.8,0.888889
2,2,layer02_candidate_enrichment,0,20,0,0,20,0.000000,0.0,0.000000,12,15,12,0,3,1.0,0.8,0.888889
3,3,layer03_candidate_typing_resolution,0,20,0,0,20,0.000000,0.0,0.000000,12,15,12,0,3,1.0,0.8,0.888889
4,4,layer04_candidate_relation_extraction,15,20,2,13,18,0.133333,0.1,0.114286,12,15,12,0,3,1.0,0.8,0.888889
5,5,layer05_candidate_triple_generation,15,20,2,13,18,0.133333,0.1,0.114286,12,15,12,0,3,1.0,0.8,0.888889
6,6,layer06_concept_relation_induction,15,20,2,13,18,0.133333,0.1,0.114286,12,15,12,0,3,1.0,0.8,0.888889
7,7,layer07_hierarchisation,15,20,2,13,18,0.133333,0.1,0.114286,12,15,12,0,3,1.0,0.8,0.888889
8,8,layer08_axiom_schemata_extraction,15,20,2,13,18,0.133333,0.1,0.114286,12,15,12,0,3,1.0,0.8,0.888889
9,9,layer09_general_axiom_extraction,15,20,2,13,18,0.133333,0.1,0.114286,12,15,12,0,3,1.0,0.8,0.888889
10,10,layer10_validation_reasoning,15,20,2,13,18,0.133333,0.1,0.114286,12,15,12,0,3,1.0,0.8,0.888889
11,11,layer11_inference_completion,15,20,2,13,18,0.133333,0.1,0.114286,12,15,12,0,3,1.0,0.8,0.888889
12,12,layer12_serialization,15,20,2,13,18,0.133333,0.1,0.114286,12,15,12,0,3,1.0,0.8,0.888889

First-failure counts
{'layer01_relation_instance_missing': 11, 'survived_to_layer05': 2, 'layer01_target_event_missing': 4, 'layer01_source_event_missing': 3}

## 5. Layer 1 validated event inventory and closed-inventory relation instances

In [6]:
layer1_rows = read_json(RUN_DIR / "run_logs/layer01_event_relation_instances.json")
layer1_df = pd.DataFrame(layer1_rows)
display(layer1_df)

accepted = layer1_df[layer1_df["status"] == "accepted"] if not layer1_df.empty else layer1_df
if not accepted.empty:
    print("Accepted event mentions:", int((accepted["label"] == "event_mention").sum()))
    print("Accepted relation instances:", int((accepted["label"] == "relation_instance").sum()))
    print("Rejected rows:", int((layer1_df["status"] == "rejected").sum()))

,phase,batch_index,assigned_source_ids,source_event_id,target_event_id,relation_cue,justification,status,reason,label,expr_id,text,relation_instance
0,relation_source_batch,2.0,"[E0008, E0009, E0010, E0011]",E0009,E0008,precondition,The 90‑day stay is a consequence of the reckle...,rejected,missing_or_canonical_relation_cue,relation_instance,NaN,NaN,NaN
1,relation_source_batch,2.0,"[E0008, E0009, E0010, E0011]",E0010,E0009,precondition,The probation violation led to the reckless dr...,rejected,missing_or_canonical_relation_cue,relation_instance,NaN,NaN,NaN
2,relation_source_batch,2.0,"[E0008, E0009, E0010, E0011]",E0011,E0009,precondition,The prior drunk driving case (driving) resulte...,rejected,missing_or_canonical_relation_cue,relation_instance,NaN,NaN,NaN
3,materialization,NaN,NaN,NaN,NaN,NaN,Explicit event.,accepted,NaN,event_mention,expr_00000,S1[2:4]::checks into,None
4,materialization,NaN,NaN,NaN,NaN,NaN,Explicit verb.,accepted,NaN,event_mention,expr_00001,S3[1:2]::skipping,None
5,materialization,NaN,NaN,NaN,NaN,NaN,Explicit verb.,accepted,NaN,event_mention,expr_00002,S3[4:5]::entering,None
6,materialization,NaN,NaN,NaN,NaN,NaN,Explicit verb.,accepted,NaN,event_mention,expr_00003,S3[11:12]::facing,None
7,materialization,NaN,NaN,NaN,NaN,NaN,Explicit eventive noun.,accepted,NaN,event_mention,expr_00004,S3[15:16]::arrest,None
8,materialization,NaN,NaN,NaN,NaN,NaN,Explicit verb.,accepted,NaN,event_mention,expr_00005,S3[17:18]::violating,None
9,materialization,NaN,NaN,NaN,NaN,NaN,Explicit verb.,accepted,NaN,event_mention,expr_00006,S3[24:26]::checked into,None
10,materialization,NaN,NaN,NaN,NaN,NaN,Explicit verb.,accepted,NaN,event_mention,expr_00007,S3[31:32]::begin,None
11,materialization,NaN,NaN,NaN,NaN,NaN,Explicit eventive noun.,accepted,NaN,event_mention,expr_00008,S3[39:40]::stay,None
12,materialization,NaN,NaN,NaN,NaN,NaN,Explicit eventive noun not previously captured.,accepted,NaN,event_mention,expr_00009,S3[44:45]::conviction,None
13,materialization,NaN,NaN,NaN,NaN,NaN,Explicit eventive noun.,accepted,NaN,event_mention,expr_00010,S4[15:16]::violation,None
14,materialization,NaN,NaN,NaN,NaN,NaN,Explicit nominalized action.,accepted,NaN,event_mention,expr_00011,S4[20:21]::driving,None
15,materialization,NaN,NaN,NaN,NaN,NaN,Explicit verb indicating arrival.,accepted,NaN,event_mention,expr_00012,S5[6:7]::comes,None
16,materialization,NaN,NaN,NaN,NaN,NaN,Hyphenated verb phrase indicating collision.,accepted,NaN,event_mention,expr_00013,S5[9:12]::rear - ended,None
17,materialization,NaN,NaN,NaN,NaN,NaN,Explicit verb indicating deception.,accepted,NaN,event_mention,expr_00014,S5[27:28]::lied,None
18,materialization,NaN,NaN,NaN,NaN,NaN,Explicit verb indicating communication.,accepted,NaN,event_mention,expr_00015,S5[31:32]::telling,None
19,materialization,NaN,NaN,NaN,NaN,NaN,Explicit state of not driving not previously c...,accepted,NaN,event_mention,expr_00016,S5[34:37]::was not driving,None
20,materialization,NaN,NaN,NaN,NaN,NaN,Explicit state of not driving.,accepted,NaN,event_mention,expr_00017,S5[36:37]::driving,None
21,materialization,NaN,NaN,NaN,NaN,NaN,Checking into the Betty Ford Center sets up th...,accepted,NaN,relation_instance,expr_00018,S1[2:4]::checks into || enables || S3[39:40]::...,"[S1[2:4]::checks into, enables, S3[39:40]::stay]"
22,materialization,NaN,NaN,NaN,NaN,NaN,Skipping out on entering a rehab facility moti...,accepted,NaN,relation_instance,expr_00019,S3[1:2]::skipping || enables || S1[2:4]::check...,"[S3[1:2]::skipping, enables, S1[2:4]::checks i..."
23,materialization,NaN,NaN,NaN,NaN,NaN,The act of entering a Newport Beach facility (...,accepted,NaN,relation_instance,expr_00020,S3[4:5]::entering || enables || S1[2:4]::check...,"[S3[4:5]::entering, enables, S1[2:4]::checks i..."
24,materialization,NaN,NaN,NaN,NaN,NaN,Facing arrest prospect motivates the check‑in.,accepted,NaN,relation_instance,expr_00021,S3[11:12]::facing || motivates || S1[2:4]::che...,"[S3[11:12]::facing, motivates, S1[2:4]::checks..."
25,materialization,NaN,NaN,NaN,NaN,NaN,Arrest is a prerequisite that leads to checkin...,accepted,NaN,relation_instance,expr_00022,S3[15:16]::arrest || enables || S3[24:26]::che...,"[S3[15:16]::arrest, enables, S3[24:26]::checke..."
26,materialization,NaN,NaN,NaN,NaN,NaN,Violation of probation is a prerequisite that ...,accepted,NaN,relation_instance,expr_00023,S3[17:18]::violating || enables || S3[15:16]::...,"[S3[17:18]::violating, enables, S3[15:16]::arr..."
27,materialization,NaN,NaN,NaN,NaN,NaN,Violation of probation is a prerequisite that ...,accepted,NaN,relation_instance,expr_00024,S3[17:18]::violating || enables || S3[24:26]::...,"[S3[17:18]::violating, enables, S3[24:26]::che..."
28,materialization,NaN,NaN,NaN,NaN,NaN,Checking into the center is a prerequisite tha...,accepted,NaN,relation_instance,expr_00025,S3[24:26]::checked into || enables || S3[31:32...,"[S3[24:26]::checked into, enables, S3[31:32]::..."
29,materialization,NaN,NaN,NaN,NaN,NaN,E0012 describes the event that precedes the st...,accepted,NaN,relation_instance,expr_00026,S5[6:7]::comes || comes after || S3[24:26]::ch...,"[S5[6:7]::comes, comes after, S3[24:26]::check..."
30,materialization,NaN,NaN,NaN,NaN,NaN,The arrival at Betty Ford initiates the 90‑day...,accepted,NaN,relation_instance,expr_00027,S5[6:7]::comes || comes after || S3[31:32]::begin,"[S5[6:7]::comes, comes after, S3[31:32]::begin]"
31,materialization,NaN,NaN,NaN,NaN,NaN,The stay itself is the consequence of the prec...,accepted,NaN,relation_instance,expr_00028,S5[6:7]::comes || comes after || S3[39:40]::stay,"[S5[6:7]::comes, comes after, S3[39:40]::stay]"
32,materialization,NaN,NaN,NaN,NaN,NaN,"The conviction is the reason for the stay, so ...",accepted,NaN,relation_instance,expr_00029,S5[6:7]::comes || comes after || S3[44:45]::co...,"[S5[6:7]::comes, comes after, S3[44:45]::convi..."
33,materialization,NaN,NaN,NaN,NaN,NaN,The rear‑ended incident is a prerequisite for ...,accepted,NaN,relation_instance,expr_00030,S5[9:12]::rear - ended || rear‑ended || S3[24:...,"[S5[9:12]::rear - ended, rear‑ended, S3[24:26]..."
34,materialization,NaN,NaN,NaN,NaN,NaN,The incident triggers the start of the stay.,accepted,NaN,relation_instance,expr_00031,S5[9:12]::rear - ended || rear‑ended || S3[31:...,"[S5[9:12]::rear - ended, rear‑ended, S3[31:32]..."
35,materialization,NaN,NaN,NaN,NaN,NaN,The incident leads to the 90‑day stay.,accepted,NaN,relation_instance,expr_00032,S5[9:12]::rear - ended || rear‑ended || S3[39:...,"[S5[9:12]::rear - ended, rear‑ended, S3[39:40]..."
36,materialization,NaN,NaN,NaN,NaN,NaN,The incident is part of the reckless driving c...,accepted,NaN,relation_instance,expr_00033,S5[9:12]::rear - ended || rear‑ended || S3[44:...,"[S5[9:12]::rear - ended, rear‑ended, S3[44:45]..."
37,materialization,NaN,NaN,NaN,NaN,NaN,The lie is a prerequisite for the stay at Bett...,accepted,NaN,relation_instance,expr_00034,S5[27:28]::lied || lied || S3[24:26]::checked ...,"[S5[27:28]::lied, lied, S3[24:26]::checked into]"
38,materialization,NaN,NaN,NaN,NaN,NaN,The lie triggers the start of the stay.,accepted,NaN,relation_instance,expr_00035,S5[27:28]::lied || lied || S3[31:32]::begin,"[S5[27:28]::lied, lied, S3[31:32]::begin]"
39,materialization,NaN,NaN,NaN,NaN,NaN,The lie leads to the 90‑day stay.,accepted,NaN,relation_instance,expr_00036,S5[27:28]::lied || lied || S3[39:40]::stay,"[S5[27:28]::lied, lied, S3[39:40]::stay]"
40,materialization,NaN,NaN,NaN,NaN,NaN,The lie is part of the reckless driving convic...,accepted,NaN,relation_instance,expr_00037,S5[27:28]::lied || lied || S3[44:45]::conviction,"[S5[27:28]::lied, lied, S3[44:45]::conviction]"
41,materialization,NaN,NaN,NaN,NaN,NaN,The telling of not driving is a prerequisite f...,accepted,NaN,relation_instance,expr_00038,S5[31:32]::telling || telling || S3[24:26]::ch...,"[S5[31:32]::telling, telling, S3[24:26]::check..."
42,materialization,NaN,NaN,NaN,NaN,NaN,The telling triggers the start of the stay.,accepted,NaN,relation_instance,expr_00039,S5[31:32]::telling || telling || S3[31:32]::begin,"[S5[31:32]::telling, telling, S3[31:32]::begin]"
43,materialization,NaN,NaN,NaN,NaN,NaN,The telling leads to the 90‑day stay.,accepted,NaN,relation_instance,expr_00040,S5[31:32]::telling || telling || S3[39:40]::stay,"[S5[31:32]::telling, telling, S3[39:40]::stay]"
44,materialization,NaN,NaN,NaN,NaN,NaN,The telling is part of the reckless driving co...,accepted,NaN,relation_instance,expr_00041,S5[31:32]::telling || telling || S3[44:45]::co...,"[S5[31:32]::telling, telling, S3[44:45]::convi..."
45,materialization,NaN,NaN,NaN,NaN,NaN,The statement that Lohan was not driving prece...,accepted,NaN,relation_instance,expr_00042,S5[34:37]::was not driving || after || S3[39:4...,"[S5[34:37]::was not driving, after, S3[39:40]:..."
46,materialization,NaN,NaN,NaN,NaN,NaN,The mention of Lohan driving (rear‑ended a tru...,accepted,NaN,relation_instance,expr_00043,S5[36:37]::driving || after || S3[39:40]::stay,"[S5[36:37]::driving, after, S3[39:40]::stay]"

Accepted event mentions: 18
Accepted relation instances: 26
Rejected rows: 3

### Layer 1A span validation/repair and Layer 1B closed-inventory audit

In [7]:
inventory_audit = pd.DataFrame(read_json(RUN_DIR / "run_logs/layer01_event_inventory.json"))
relation_generation = pd.DataFrame(read_json(RUN_DIR / "run_logs/layer01_relation_generation.json"))
call_audit = pd.DataFrame(read_json(RUN_DIR / "run_logs/layer01_call_audit.json"))

print("Layer 1A event inventory audit")
display(inventory_audit)
if not inventory_audit.empty:
    print("Accepted validated events:", int((inventory_audit["status"] == "accepted").sum()))
    print("Rejected event proposals:", int((inventory_audit["status"] == "rejected").sum()))
    if "repaired" in inventory_audit:
        print("Source-token span repairs:", int(inventory_audit["repaired"].fillna(False).sum()))

print("Layer 1B relation generation audit")
display(relation_generation)
if not relation_generation.empty:
    print("Accepted closed-inventory pairs:", int((relation_generation["status"] == "accepted").sum()))
    print("Rejected pair proposals:", int((relation_generation["status"] == "rejected").sum()))

print("Layer 1 sentence/review/source-batch call audit")
display(call_audit)
if not call_audit.empty:
    display(call_audit.groupby(["phase", "status"], dropna=False).size().reset_index(name="calls"))

Layer 1A event inventory audit

,raw_item,proposed_event_key,proposed_sentence_id,proposed_token_start,proposed_token_end,proposed_trigger,repair_steps,status,reason,canonical_event_key,sentence_id,token_start,token_end,repaired_trigger,repaired,phase,justification
0,"{'sentence_id': 1, 'token_start': 2, 'token_en...",None,1,2,4,checks into,[],accepted,validated_source_token_span,S1[2:4]::checks into,1,2,4,checks into,False,sentence_inventory,Explicit event.
1,"{'sentence_id': 3, 'token_start': 1, 'token_en...",None,3,1,2,skipping,[],accepted,validated_source_token_span,S3[1:2]::skipping,3,1,2,skipping,False,sentence_inventory,Explicit verb.
2,"{'sentence_id': 3, 'token_start': 4, 'token_en...",None,3,4,5,entering,[],accepted,validated_source_token_span,S3[4:5]::entering,3,4,5,entering,False,sentence_inventory,Explicit verb.
3,"{'sentence_id': 3, 'token_start': 11, 'token_e...",None,3,11,12,facing,[],accepted,validated_source_token_span,S3[11:12]::facing,3,11,12,facing,False,sentence_inventory,Explicit verb.
4,"{'sentence_id': 3, 'token_start': 15, 'token_e...",None,3,15,16,arrest,[],accepted,validated_source_token_span,S3[15:16]::arrest,3,15,16,arrest,False,sentence_inventory,Explicit eventive noun.
5,"{'sentence_id': 3, 'token_start': 17, 'token_e...",None,3,17,18,violating,[],accepted,validated_source_token_span,S3[17:18]::violating,3,17,18,violating,False,sentence_inventory,Explicit verb.
6,"{'sentence_id': 3, 'token_start': 24, 'token_e...",None,3,24,25,checked,[completed_phrasal_verb_particle],accepted,validated_source_token_span,S3[24:26]::checked into,3,24,26,checked into,True,sentence_inventory,Explicit verb.
7,"{'sentence_id': 3, 'token_start': 31, 'token_e...",None,3,31,32,begin,[],accepted,validated_source_token_span,S3[31:32]::begin,3,31,32,begin,False,sentence_inventory,Explicit verb.
8,"{'sentence_id': 3, 'token_start': 39, 'token_e...",None,3,39,40,stay,[],accepted,validated_source_token_span,S3[39:40]::stay,3,39,40,stay,False,sentence_inventory,Explicit eventive noun.
9,"{'sentence_id': 4, 'token_start': 14, 'token_e...",None,4,14,15,violation,[aligned_to_complete_trigger_text],accepted,validated_source_token_span,S4[15:16]::violation,4,15,16,violation,True,sentence_inventory,Explicit eventive noun.
10,"{'sentence_id': 4, 'token_start': 20, 'token_e...",None,4,20,21,driving,[],accepted,validated_source_token_span,S4[20:21]::driving,4,20,21,driving,False,sentence_inventory,Explicit nominalized action.
11,"{'sentence_id': 5, 'token_start': 6, 'token_en...",None,5,6,7,comes,[],accepted,validated_source_token_span,S5[6:7]::comes,5,6,7,comes,False,sentence_inventory,Explicit verb indicating arrival.
12,"{'sentence_id': 5, 'token_start': 9, 'token_en...",None,5,9,12,rear-ended,[],accepted,validated_source_token_span,S5[9:12]::rear - ended,5,9,12,rear - ended,False,sentence_inventory,Hyphenated verb phrase indicating collision.
13,"{'sentence_id': 5, 'token_start': 27, 'token_e...",None,5,27,28,lied,[],accepted,validated_source_token_span,S5[27:28]::lied,5,27,28,lied,False,sentence_inventory,Explicit verb indicating deception.
14,"{'sentence_id': 5, 'token_start': 31, 'token_e...",None,5,31,32,telling,[],accepted,validated_source_token_span,S5[31:32]::telling,5,31,32,telling,False,sentence_inventory,Explicit verb indicating communication.
15,"{'sentence_id': 5, 'token_start': 36, 'token_e...",None,5,36,37,driving,[],accepted,validated_source_token_span,S5[36:37]::driving,5,36,37,driving,False,sentence_inventory,Explicit state of not driving.
16,"{'sentence_id': 5, 'token_start': 6, 'token_en...",None,5,6,7,comes,[],accepted,validated_source_token_span,S5[6:7]::comes,5,6,7,comes,False,coverage_review_1,Missing explicit event.
17,"{'sentence_id': 3, 'token_start': 44, 'token_e...",None,3,44,45,conviction,[],accepted,validated_source_token_span,S3[44:45]::conviction,3,44,45,conviction,False,coverage_review_2,Explicit eventive noun not previously captured.
18,"{'sentence_id': 5, 'token_start': 34, 'token_e...",None,5,34,37,was not driving,[],accepted,validated_source_token_span,S5[34:37]::was not driving,5,34,37,was not driving,False,coverage_review_2,Explicit state of not driving not previously c...

Accepted validated events: 19
Rejected event proposals: 0
Source-token span repairs: 2
Layer 1B relation generation audit

,phase,batch_index,assigned_source_ids,source_event_id,target_event_id,relation_cue,justification,status,reason,relation_instance
0,relation_source_batch,0,"[E0000, E0001, E0002, E0003]",E0000,E0008,enables,Checking into the Betty Ford Center sets up th...,accepted,closed_inventory_source_batch_relation,S1[2:4]::checks into || enables || S3[39:40]::...
1,relation_source_batch,0,"[E0000, E0001, E0002, E0003]",E0001,E0000,enables,Skipping out on entering a rehab facility moti...,accepted,closed_inventory_source_batch_relation,S3[1:2]::skipping || enables || S1[2:4]::check...
2,relation_source_batch,0,"[E0000, E0001, E0002, E0003]",E0002,E0000,enables,The act of entering a Newport Beach facility (...,accepted,closed_inventory_source_batch_relation,S3[4:5]::entering || enables || S1[2:4]::check...
3,relation_source_batch,0,"[E0000, E0001, E0002, E0003]",E0003,E0000,motivates,Facing arrest prospect motivates the check‑in.,accepted,closed_inventory_source_batch_relation,S3[11:12]::facing || motivates || S1[2:4]::che...
4,relation_source_batch,1,"[E0004, E0005, E0006, E0007]",E0004,E0006,enables,Arrest is a prerequisite that leads to checkin...,accepted,closed_inventory_source_batch_relation,S3[15:16]::arrest || enables || S3[24:26]::che...
5,relation_source_batch,1,"[E0004, E0005, E0006, E0007]",E0005,E0004,enables,Violation of probation is a prerequisite that ...,accepted,closed_inventory_source_batch_relation,S3[17:18]::violating || enables || S3[15:16]::...
6,relation_source_batch,1,"[E0004, E0005, E0006, E0007]",E0005,E0006,enables,Violation of probation is a prerequisite that ...,accepted,closed_inventory_source_batch_relation,S3[17:18]::violating || enables || S3[24:26]::...
7,relation_source_batch,1,"[E0004, E0005, E0006, E0007]",E0006,E0007,enables,Checking into the center is a prerequisite tha...,accepted,closed_inventory_source_batch_relation,S3[24:26]::checked into || enables || S3[31:32...
8,relation_source_batch,2,"[E0008, E0009, E0010, E0011]",E0009,E0008,precondition,The 90‑day stay is a consequence of the reckle...,rejected,missing_or_canonical_relation_cue,NaN
9,relation_source_batch,2,"[E0008, E0009, E0010, E0011]",E0010,E0009,precondition,The probation violation led to the reckless dr...,rejected,missing_or_canonical_relation_cue,NaN
10,relation_source_batch,2,"[E0008, E0009, E0010, E0011]",E0011,E0009,precondition,The prior drunk driving case (driving) resulte...,rejected,missing_or_canonical_relation_cue,NaN
11,relation_source_batch,3,"[E0012, E0013, E0014, E0015]",E0012,E0006,comes after,E0012 describes the event that precedes the st...,accepted,closed_inventory_source_batch_relation,S5[6:7]::comes || comes after || S3[24:26]::ch...
12,relation_source_batch,3,"[E0012, E0013, E0014, E0015]",E0012,E0007,comes after,The arrival at Betty Ford initiates the 90‑day...,accepted,closed_inventory_source_batch_relation,S5[6:7]::comes || comes after || S3[31:32]::begin
13,relation_source_batch,3,"[E0012, E0013, E0014, E0015]",E0012,E0008,comes after,The stay itself is the consequence of the prec...,accepted,closed_inventory_source_batch_relation,S5[6:7]::comes || comes after || S3[39:40]::stay
14,relation_source_batch,3,"[E0012, E0013, E0014, E0015]",E0012,E0009,comes after,"The conviction is the reason for the stay, so ...",accepted,closed_inventory_source_batch_relation,S5[6:7]::comes || comes after || S3[44:45]::co...
15,relation_source_batch,3,"[E0012, E0013, E0014, E0015]",E0013,E0006,rear‑ended,The rear‑ended incident is a prerequisite for ...,accepted,closed_inventory_source_batch_relation,S5[9:12]::rear - ended || rear‑ended || S3[24:...
16,relation_source_batch,3,"[E0012, E0013, E0014, E0015]",E0013,E0007,rear‑ended,The incident triggers the start of the stay.,accepted,closed_inventory_source_batch_relation,S5[9:12]::rear - ended || rear‑ended || S3[31:...
17,relation_source_batch,3,"[E0012, E0013, E0014, E0015]",E0013,E0008,rear‑ended,The incident leads to the 90‑day stay.,accepted,closed_inventory_source_batch_relation,S5[9:12]::rear - ended || rear‑ended || S3[39:...
18,relation_source_batch,3,"[E0012, E0013, E0014, E0015]",E0013,E0009,rear‑ended,The incident is part of the reckless driving c...,accepted,closed_inventory_source_batch_relation,S5[9:12]::rear - ended || rear‑ended || S3[44:...
19,relation_source_batch,3,"[E0012, E0013, E0014, E0015]",E0014,E0006,lied,The lie is a prerequisite for the stay at Bett...,accepted,closed_inventory_source_batch_relation,S5[27:28]::lied || lied || S3[24:26]::checked ...
20,relation_source_batch,3,"[E0012, E0013, E0014, E0015]",E0014,E0007,lied,The lie triggers the start of the stay.,accepted,closed_inventory_source_batch_relation,S5[27:28]::lied || lied || S3[31:32]::begin
21,relation_source_batch,3,"[E0012, E0013, E0014, E0015]",E0014,E0008,lied,The lie leads to the 90‑day stay.,accepted,closed_inventory_source_batch_relation,S5[27:28]::lied || lied || S3[39:40]::stay
22,relation_source_batch,3,"[E0012, E0013, E0014, E0015]",E0014,E0009,lied,The lie is part of the reckless driving convic...,accepted,closed_inventory_source_batch_relation,S5[27:28]::lied || lied || S3[44:45]::conviction
23,relation_source_batch,3,"[E0012, E0013, E0014, E0015]",E0015,E0006,telling,The telling of not driving is a prerequisite f...,accepted,closed_inventory_source_batch_relation,S5[31:32]::telling || telling || S3[24:26]::ch...
24,relation_source_batch,3,"[E0012, E0013, E0014, E0015]",E0015,E0007,telling,The telling triggers the start of the stay.,accepted,closed_inventory_source_batch_relation,S5[31:32]::telling || telling || S3[31:32]::begin
25,relation_source_batch,3,"[E0012, E0013, E0014, E0015]",E0015,E0008,telling,The telling leads to the 90‑day stay.,accepted,closed_inventory_source_batch_relation,S5[31:32]::telling || telling || S3[39:40]::stay
26,relation_source_batch,3,"[E0012, E0013, E0014, E0015]",E0015,E0009,telling,The telling is part of the reckless driving co...,accepted,closed_inventory_source_batch_relation,S5[31:32]::telling || telling || S3[44:45]::co...
27,relation_source_batch,4,"[E0016, E0017]",E0016,E0008,after,The statement that Lohan was not driving prece...,accepted,closed_inventory_source_batch_relation,S5[34:37]::was not driving || after || S3[39:4...
28,relation_source_batch,4,"[E0016, E0017]",E0017,E0008,after,The mention of Lohan driving (rear‑ended a tru...,accepted,closed_inventory_source_batch_relation,S5[36:37]::driving || after || S3[39:40]::stay

Accepted closed-inventory pairs: 26
Rejected pair proposals: 3
Layer 1 sentence/review/source-batch call audit

,phase,sentence_id,status,reason,proposals,new_validated_events,pass_index,inventory_size_after,batch_index,assigned_source_ids
0,sentence_inventory,0.0,skipped,url_sentence,NaN,NaN,NaN,NaN,NaN,NaN
1,sentence_inventory,2.0,skipped,date_or_publication_metadata,NaN,NaN,NaN,NaN,NaN,NaN
2,sentence_inventory,1.0,ok,NaN,1.0,1.0,NaN,NaN,NaN,NaN
3,sentence_inventory,3.0,ok,NaN,8.0,8.0,NaN,NaN,NaN,NaN
4,sentence_inventory,4.0,ok,NaN,2.0,2.0,NaN,NaN,NaN,NaN
5,sentence_inventory,5.0,ok,NaN,5.0,5.0,NaN,NaN,NaN,NaN
6,coverage_review,NaN,ok,NaN,1.0,0.0,1.0,16.0,NaN,NaN
7,coverage_review,NaN,ok,NaN,2.0,2.0,2.0,18.0,NaN,NaN
8,relation_source_batch,NaN,ok,NaN,4.0,NaN,NaN,NaN,1.0,"[E0004, E0005, E0006, E0007]"
9,relation_source_batch,NaN,ok,NaN,2.0,NaN,NaN,NaN,4.0,"[E0016, E0017]"
10,relation_source_batch,NaN,ok,NaN,3.0,NaN,NaN,NaN,2.0,"[E0008, E0009, E0010, E0011]"
11,relation_source_batch,NaN,ok,NaN,16.0,NaN,NaN,NaN,3.0,"[E0012, E0013, E0014, E0015]"
12,relation_source_batch,NaN,ok,NaN,4.0,NaN,NaN,NaN,0.0,"[E0000, E0001, E0002, E0003]"

                   phase   status  calls
0        coverage_review       ok      2
1  relation_source_batch       ok      5
2     sentence_inventory       ok      4
3     sentence_inventory  skipped      2

## 6. Parallel Layer 2 ontology decisions

In [8]:
layer2 = pd.DataFrame(read_json(RUN_DIR / "run_logs/layer02_relation_decisions.json"))
prompt_audit = pd.DataFrame(read_json(RUN_DIR / "run_logs/layer02_compact_prompt_audit.json"))

display(layer2)
print("Compact prompt audit")
display(prompt_audit)
if not prompt_audit.empty:
    print("Layer 2 calls:", len(prompt_audit))
    print("Mean Layer 2 user characters:", round(prompt_audit["user_chars"].mean(), 1))
    print("Maximum Layer 2 user characters:", int(prompt_audit["user_chars"].max()))
    print("Candidates per decision:", sorted(set(len(x) for x in prompt_audit["candidate_relation_ids"])))

,expr_id,relation_instance,source,predicate,target,found,selected_relation_id,canonical_relation,decision,ontology_hints
0,expr_00018,S1[2:4]::checks into || enables || S3[39:40]::...,S1[2:4]::checks into,enables,S3[39:40]::stay,True,PRECONDITION,PRECONDITION,The act of checking into the Betty Ford Center...,"[controlled_relation:PRECONDITION, promote_to_..."
1,expr_00019,S3[1:2]::skipping || enables || S1[2:4]::check...,S3[1:2]::skipping,enables,S1[2:4]::checks into,True,PRECONDITION,PRECONDITION,Skipping out on entering a rehab facility crea...,"[controlled_relation:PRECONDITION, promote_to_..."
2,expr_00020,S3[4:5]::entering || enables || S1[2:4]::check...,S3[4:5]::entering,enables,S1[2:4]::checks into,True,PRECONDITION,PRECONDITION,The act of entering a facility motivates and e...,"[controlled_relation:PRECONDITION, promote_to_..."
3,expr_00021,S3[11:12]::facing || motivates || S1[2:4]::che...,S3[11:12]::facing,motivates,S1[2:4]::checks into,True,PRECONDITION,PRECONDITION,The source event (facing arrest prospect) serv...,"[controlled_relation:PRECONDITION, promote_to_..."
4,expr_00022,S3[15:16]::arrest || enables || S3[24:26]::che...,S3[15:16]::arrest,enables,S3[24:26]::checked into,True,PRECONDITION,PRECONDITION,The arrest establishes a prerequisite conditio...,"[controlled_relation:PRECONDITION, promote_to_..."
5,expr_00023,S3[17:18]::violating || enables || S3[15:16]::...,S3[17:18]::violating,enables,S3[15:16]::arrest,True,PRECONDITION,PRECONDITION,Violation of probation is a prerequisite that ...,"[controlled_relation:PRECONDITION, promote_to_..."
6,expr_00024,S3[17:18]::violating || enables || S3[24:26]::...,S3[17:18]::violating,enables,S3[24:26]::checked into,True,PRECONDITION,PRECONDITION,Violation of probation is a prerequisite that ...,"[controlled_relation:PRECONDITION, promote_to_..."
7,expr_00025,S3[24:26]::checked into || enables || S3[31:32...,S3[24:26]::checked into,enables,S3[31:32]::begin,True,PRECONDITION,PRECONDITION,The act of checking into the center establishe...,"[controlled_relation:PRECONDITION, promote_to_..."
8,expr_00026,S5[6:7]::comes || comes after || S3[24:26]::ch...,S5[6:7]::comes,comes after,S3[24:26]::checked into,True,FALLING_ACTION,FALLING_ACTION,The source event 'comes' occurs after the targ...,"[controlled_relation:FALLING_ACTION, promote_t..."
9,expr_00027,S5[6:7]::comes || comes after || S3[31:32]::begin,S5[6:7]::comes,comes after,S3[31:32]::begin,True,PRECONDITION,PRECONDITION,The arrival event (comes) is the prerequisite ...,"[controlled_relation:PRECONDITION, promote_to_..."
10,expr_00028,S5[6:7]::comes || comes after || S3[39:40]::stay,S5[6:7]::comes,comes after,S3[39:40]::stay,False,NaN,NaN,"The source event occurs after the target, so i...","[promote_to_ontology:false, source_label:S5[6:..."
11,expr_00029,S5[6:7]::comes || comes after || S3[44:45]::co...,S5[6:7]::comes,comes after,S3[44:45]::conviction,True,PRECONDITION,PRECONDITION,The conviction establishes the necessary conte...,"[controlled_relation:PRECONDITION, promote_to_..."
12,expr_00030,S5[9:12]::rear - ended || rear‑ended || S3[24:...,S5[9:12]::rear - ended,rear‑ended,S3[24:26]::checked into,True,PRECONDITION,PRECONDITION,The rear‑ended incident establishes a necessar...,"[controlled_relation:PRECONDITION, promote_to_..."
13,expr_00031,S5[9:12]::rear - ended || rear‑ended || S3[31:...,S5[9:12]::rear - ended,rear‑ended,S3[31:32]::begin,True,PRECONDITION,PRECONDITION,The rear‑ended incident establishes the necess...,"[controlled_relation:PRECONDITION, promote_to_..."
14,expr_00032,S5[9:12]::rear - ended || rear‑ended || S3[39:...,S5[9:12]::rear - ended,rear‑ended,S3[39:40]::stay,True,FALLING_ACTION,FALLING_ACTION,The rear‑ended incident directly leads to the ...,"[controlled_relation:FALLING_ACTION, promote_t..."
15,expr_00033,S5[9:12]::rear - ended || rear‑ended || S3[44:...,S5[9:12]::rear - ended,rear‑ended,S3[44:45]::conviction,True,FALLING_ACTION,FALLING_ACTION,The rear‑ended incident is a narrative precurs...,"[controlled_relation:FALLING_ACTION, promote_t..."
16,expr_00034,S5[27:28]::lied || lied || S3[24:26]::checked ...,S5[27:28]::lied,lied,S3[24:26]::checked into,True,PRECONDITION,PRECONDITION,The lie is a prerequisite that enables the sub...,"[controlled_relation:PRECONDITION, promote_to_..."
17,expr_00035,S5[27:28]::lied || lied || S3[31:32]::begin,S5[27:28]::lied,lied,S3[31:32]::begin,True,PRECONDITION,PRECONDITION,The lie acts as a prerequisite that triggers t...,"[controlled_relation:PRECONDITION, promote_to_..."
18,expr_00036,S5[27:28]::lied || lied || S3[39:40]::stay,S5[27:28]::lied,lied,S3[39:40]::stay,True,PRECONDITION,PRECONDITION,The lie establishes a prerequisite that leads ...,"[controlled_relation:PRECONDITION, promote_to_..."
19,expr_00037,S5[27:28]::lied || lied || S3[44:45]::conviction,S5[27:28]::lied,lied,S3[44:45]::conviction,True,PRECONDITION,PRECONDITION,The lie is a prerequisite that enabled the rec...,"[controlled_relation:PRECONDITION, promote_to_..."
20,expr_00038,S5[31:32]::telling || telling || S3[24:26]::ch...,S5[31:32]::telling,telling,S3[24:26]::checked into,True,PRECONDITION,PRECONDITION,The telling of not driving establishes a prere...,"[controlled_relation:PRECONDITION, promote_to_..."
21,expr_00039,S5[31:32]::telling || telling || S3[31:32]::begin,S5[31:32]::telling,telling,S3[31:32]::begin,True,PRECONDITION,PRECONDITION,telling establishes the necessary condition fo...,"[controlled_relation:PRECONDITION, promote_to_..."
22,expr_00040,S5[31:32]::telling || telling || S3[39:40]::stay,S5[31:32]::telling,telling,S3[39:40]::stay,True,PRECONDITION,PRECONDITION,The telling establishes a prerequisite that en...,"[controlled_relation:PRECONDITION, promote_to_..."
23,expr_00041,S5[31:32]::telling || telling || S3[44:45]::co...,S5[31:32]::telling,telling,S3[44:45]::conviction,True,PRECONDITION,PRECONDITION,The telling supplies evidence that leads to th...,"[controlled_relation:PRECONDITION, promote_to_..."
24,expr_00042,S5[34:37]::was not driving || after || S3[39:4...,S5[34:37]::was not driving,after,S3[39:40]::stay,True,FALLING_ACTION,FALLING_ACTION,The event 'was not driving' precedes and leads...,"[controlled_relation:FALLING_ACTION, promote_t..."
25,expr_00043,S5[36:37]::driving || after || S3[39:40]::stay,S5[36:37]::driving,after,S3[39:40]::stay,True,PRECONDITION,PRECONDITION,"The driving event occurs after the stay, indic...","[controlled_relation:PRECONDITION, promote_to_..."

Compact prompt audit

,expr_id,relation_instance,candidate_relation_ids,system_chars,user_chars
0,expr_00018,S1[2:4]::checks into || enables || S3[39:40]::...,"[PRECONDITION, FALLING_ACTION]",955,5007
1,expr_00019,S3[1:2]::skipping || enables || S1[2:4]::check...,"[PRECONDITION, FALLING_ACTION]",955,5025
2,expr_00020,S3[4:5]::entering || enables || S1[2:4]::check...,"[PRECONDITION, FALLING_ACTION]",955,5036
3,expr_00021,S3[11:12]::facing || motivates || S1[2:4]::che...,"[PRECONDITION, FALLING_ACTION]",955,4003
4,expr_00022,S3[15:16]::arrest || enables || S3[24:26]::che...,"[PRECONDITION, FALLING_ACTION]",955,5016
5,expr_00023,S3[17:18]::violating || enables || S3[15:16]::...,"[PRECONDITION, FALLING_ACTION]",955,5011
6,expr_00024,S3[17:18]::violating || enables || S3[24:26]::...,"[PRECONDITION, FALLING_ACTION]",955,5035
7,expr_00025,S3[24:26]::checked into || enables || S3[31:32...,"[PRECONDITION, FALLING_ACTION]",955,5027
8,expr_00026,S5[6:7]::comes || comes after || S3[24:26]::ch...,"[PRECONDITION, FALLING_ACTION]",955,4544
9,expr_00027,S5[6:7]::comes || comes after || S3[31:32]::begin,"[PRECONDITION, FALLING_ACTION]",955,4526
10,expr_00028,S5[6:7]::comes || comes after || S3[39:40]::stay,"[PRECONDITION, FALLING_ACTION]",955,4532
11,expr_00029,S5[6:7]::comes || comes after || S3[44:45]::co...,"[PRECONDITION, FALLING_ACTION]",955,4534
12,expr_00030,S5[9:12]::rear - ended || rear‑ended || S3[24:...,"[PRECONDITION, FALLING_ACTION]",955,4499
13,expr_00031,S5[9:12]::rear - ended || rear‑ended || S3[31:...,"[PRECONDITION, FALLING_ACTION]",955,4467
14,expr_00032,S5[9:12]::rear - ended || rear‑ended || S3[39:...,"[PRECONDITION, FALLING_ACTION]",955,4460
15,expr_00033,S5[9:12]::rear - ended || rear‑ended || S3[44:...,"[PRECONDITION, FALLING_ACTION]",955,4507
16,expr_00034,S5[27:28]::lied || lied || S3[24:26]::checked ...,"[PRECONDITION, FALLING_ACTION]",955,4594
17,expr_00035,S5[27:28]::lied || lied || S3[31:32]::begin,"[PRECONDITION, FALLING_ACTION]",955,4573
18,expr_00036,S5[27:28]::lied || lied || S3[39:40]::stay,"[PRECONDITION, FALLING_ACTION]",955,4566
19,expr_00037,S5[27:28]::lied || lied || S3[44:45]::conviction,"[PRECONDITION, FALLING_ACTION]",955,4590
20,expr_00038,S5[31:32]::telling || telling || S3[24:26]::ch...,"[PRECONDITION, FALLING_ACTION]",955,4975
21,expr_00039,S5[31:32]::telling || telling || S3[31:32]::begin,"[PRECONDITION, FALLING_ACTION]",955,4953
22,expr_00040,S5[31:32]::telling || telling || S3[39:40]::stay,"[PRECONDITION, FALLING_ACTION]",955,4946
23,expr_00041,S5[31:32]::telling || telling || S3[44:45]::co...,"[PRECONDITION, FALLING_ACTION]",955,4970
24,expr_00042,S5[34:37]::was not driving || after || S3[39:4...,"[PRECONDITION, FALLING_ACTION]",955,4253
25,expr_00043,S5[36:37]::driving || after || S3[39:40]::stay,"[PRECONDITION, FALLING_ACTION]",955,4249

Layer 2 calls: 26
Mean Layer 2 user characters: 4688.4
Maximum Layer 2 user characters: 5036
Candidates per decision: [2]

## 7. Strict gold-relation trace

In [9]:
trace_df = pd.read_csv(RUN_DIR / "analysis/gold_relation_trace.csv")
display(trace_df)
display(
    trace_df.groupby("first_failure", dropna=False)
    .size()
    .reset_index(name="gold_relations")
    .sort_values("gold_relations", ascending=False)
)

,source_event_id,relation_id,target_event_id,source_keys,target_keys,first_failure
0,EVENT_2ea9a901cc230afcc371bcffee02a551,FALLING_ACTION,EVENT_401ce8fe35db27ca7b5f7cf83acc4084,"[""S3[39:40]::stay""]","[""S5[9:12]::rear - ended""]",layer01_relation_instance_missing
1,EVENT_2ea9a901cc230afcc371bcffee02a551,FALLING_ACTION,EVENT_7d29e127b36f34a94ceb0f13f9ea3a3b,"[""S3[39:40]::stay""]","[""S3[44:45]::conviction""]",layer01_relation_instance_missing
2,EVENT_2ea9a901cc230afcc371bcffee02a551,FALLING_ACTION,EVENT_a8934f381d6d835057ba8c537386ff9e,"[""S3[39:40]::stay""]","[""S5[27:28]::lied""]",layer01_relation_instance_missing
3,EVENT_2ea9a901cc230afcc371bcffee02a551,FALLING_ACTION,EVENT_f83b48c549abe22d26dc21624d8de397,"[""S3[39:40]::stay""]","[""S5[31:32]::telling""]",layer01_relation_instance_missing
4,EVENT_34cccabacad4dea93d3e762114dc05cd,FALLING_ACTION,EVENT_b79df11f8737f700691af4f8a7132190,"[""S1[2:4]::checks into""]","[""S3[4:5]::entering""]",layer01_relation_instance_missing
5,EVENT_34cccabacad4dea93d3e762114dc05cd,FALLING_ACTION,EVENT_c332a6b60af0495f34856f112dc68632,"[""S1[2:4]::checks into""]","[""S3[15:16]::arrest""]",layer01_relation_instance_missing
6,EVENT_34cccabacad4dea93d3e762114dc05cd,PRECONDITION,EVENT_2ea9a901cc230afcc371bcffee02a551,"[""S1[2:4]::checks into""]","[""S3[39:40]::stay""]",survived_to_layer05
7,EVENT_34cccabacad4dea93d3e762114dc05cd,PRECONDITION,EVENT_a6c700ffee90bb400461d1687e2287b9,"[""S1[2:4]::checks into""]","[""S5[2:3]::stay""]",layer01_target_event_missing
8,EVENT_434faad0c9ec71baa6a91df3c385299b,FALLING_ACTION,EVENT_70540222392ed30d611c5073a5b3204c,"[""S4[15:16]::violation""]","[""S4[21:22]::case""]",layer01_target_event_missing
9,EVENT_7d29e127b36f34a94ceb0f13f9ea3a3b,PRECONDITION,EVENT_a6c700ffee90bb400461d1687e2287b9,"[""S3[44:45]::conviction""]","[""S5[2:3]::stay""]",layer01_target_event_missing
10,EVENT_a6c700ffee90bb400461d1687e2287b9,FALLING_ACTION,EVENT_401ce8fe35db27ca7b5f7cf83acc4084,"[""S5[2:3]::stay""]","[""S5[9:12]::rear - ended""]",layer01_source_event_missing
11,EVENT_a6c700ffee90bb400461d1687e2287b9,FALLING_ACTION,EVENT_a8934f381d6d835057ba8c537386ff9e,"[""S5[2:3]::stay""]","[""S5[27:28]::lied""]",layer01_source_event_missing
12,EVENT_a6c700ffee90bb400461d1687e2287b9,FALLING_ACTION,EVENT_f83b48c549abe22d26dc21624d8de397,"[""S5[2:3]::stay""]","[""S5[31:32]::telling""]",layer01_source_event_missing
13,EVENT_a8934f381d6d835057ba8c537386ff9e,FALLING_ACTION,EVENT_89d0247006cb23119f629915dbc5aec7,"[""S5[27:28]::lied""]","[""S5[36:37]::driving""]",layer01_relation_instance_missing
14,EVENT_b79df11f8737f700691af4f8a7132190,PRECONDITION,EVENT_d7aec1e4ff20c3264f9fb7686355eb8a,"[""S3[4:5]::entering""]","[""S3[24:26]::checked into""]",layer01_relation_instance_missing
15,EVENT_c332a6b60af0495f34856f112dc68632,FALLING_ACTION,EVENT_9c07ef70f303f23dd82b32fb28a61ecb,"[""S3[15:16]::arrest""]","[""S3[17:18]::violating""]",layer01_relation_instance_missing
16,EVENT_c332a6b60af0495f34856f112dc68632,PRECONDITION,EVENT_d7aec1e4ff20c3264f9fb7686355eb8a,"[""S3[15:16]::arrest""]","[""S3[24:26]::checked into""]",survived_to_layer05
17,EVENT_d7aec1e4ff20c3264f9fb7686355eb8a,PRECONDITION,EVENT_2ea9a901cc230afcc371bcffee02a551,"[""S3[24:26]::checked into""]","[""S3[39:40]::stay""]",layer01_relation_instance_missing
18,EVENT_d7aec1e4ff20c3264f9fb7686355eb8a,PRECONDITION,EVENT_a6c700ffee90bb400461d1687e2287b9,"[""S3[24:26]::checked into""]","[""S5[2:3]::stay""]",layer01_target_event_missing
19,EVENT_f83b48c549abe22d26dc21624d8de397,FALLING_ACTION,EVENT_89d0247006cb23119f629915dbc5aec7,"[""S5[31:32]::telling""]","[""S5[36:37]::driving""]",layer01_relation_instance_missing

                       first_failure  gold_relations
0  layer01_relation_instance_missing              11
2       layer01_target_event_missing               4
1       layer01_source_event_missing               3
3                survived_to_layer05               2

## 8. Native event candidates, assertions and triples

In [10]:
states = {index: state for index, _, state in load_layer_states(RUN_DIR)}
layer3 = states.get(3)
layer4 = states.get(4)
layer5 = states.get(5)
layer6 = states.get(6)
layer11 = states.get(11)

if layer3:
    print("Layer 3 event candidates")
    display(pd.DataFrame([{
        "candidate_id": c.candidate_id,
        "canonical_label": c.canonical_label,
        "mentions": [m.text for m in c.mentions],
        "ontology_hints": c.ontology_hints,
    } for c in layer3.event_candidates or []]))

    print("Layer 3 relation candidates")
    display(pd.DataFrame([{
        "candidate_id": c.candidate_id,
        "canonical_label": c.canonical_label,
        "mentions": [m.text for m in c.mentions],
        "controlled_hints": [h for h in c.ontology_hints if str(h).lower().startswith("controlled_relation:")],
    } for c in layer3.relation_candidates or []]))
    assert all(c.mentions for c in layer3.relation_candidates or []), "Mention-free relation candidate detected."

if layer4:
    print("Layer 4 assertions")
    display(pd.DataFrame([{
        "source": x.source_candidate_label,
        "predicate": x.relation_label,
        "target": x.target_candidate_label,
        "confidence": x.confidence,
    } for x in layer4.candidate_relation_assertions or []]))

if layer5:
    print("Layer 5 triples")
    display(pd.DataFrame([{
        "subject": x.subject_label,
        "predicate": x.predicate_label,
        "object": x.object_label,
        "confidence": x.confidence,
    } for x in layer5.candidate_triples or []]))

print("Layer 6 ontology relation candidates:", len(layer6.ontology_relation_candidates or []) if layer6 else None)
print("Layer 11 completion candidates:", len(layer11.completion_candidates or []) if layer11 else None)

Layer 3 event candidates

,candidate_id,canonical_label,mentions,ontology_hints
0,cand_s_00000,S1[2:4]::checks into,[S1[2:4]::checks into],"[semantic_role:event_mention, candidate_family..."
1,cand_s_00001,S3[1:2]::skipping,[S3[1:2]::skipping],"[semantic_role:event_mention, candidate_family..."
2,cand_s_00002,S3[4:5]::entering,[S3[4:5]::entering],"[semantic_role:event_mention, candidate_family..."
3,cand_s_00003,S3[11:12]::facing,[S3[11:12]::facing],"[semantic_role:event_mention, candidate_family..."
4,cand_s_00004,S3[15:16]::arrest,[S3[15:16]::arrest],"[semantic_role:event_mention, candidate_family..."
5,cand_s_00005,S3[17:18]::violating,[S3[17:18]::violating],"[semantic_role:event_mention, candidate_family..."
6,cand_s_00006,S3[24:26]::checked into,[S3[24:26]::checked into],"[semantic_role:event_mention, candidate_family..."
7,cand_s_00007,S3[31:32]::begin,[S3[31:32]::begin],"[semantic_role:event_mention, candidate_family..."
8,cand_s_00008,S3[39:40]::stay,[S3[39:40]::stay],"[semantic_role:event_mention, candidate_family..."
9,cand_s_00009,S3[44:45]::conviction,[S3[44:45]::conviction],"[semantic_role:event_mention, candidate_family..."
10,cand_s_00010,S4[15:16]::violation,[S4[15:16]::violation],"[semantic_role:event_mention, candidate_family..."
11,cand_s_00011,S4[20:21]::driving,[S4[20:21]::driving],"[semantic_role:event_mention, candidate_family..."
12,cand_s_00012,S5[6:7]::comes,[S5[6:7]::comes],"[semantic_role:event_mention, candidate_family..."
13,cand_s_00013,S5[9:12]::rear - ended,[S5[9:12]::rear - ended],"[semantic_role:event_mention, candidate_family..."
14,cand_s_00014,S5[27:28]::lied,[S5[27:28]::lied],"[semantic_role:event_mention, candidate_family..."
15,cand_s_00015,S5[31:32]::telling,[S5[31:32]::telling],"[semantic_role:event_mention, candidate_family..."
16,cand_s_00016,S5[34:37]::was not driving,[S5[34:37]::was not driving],"[semantic_role:event_mention, candidate_family..."
17,cand_s_00017,S5[36:37]::driving,[S5[36:37]::driving],"[semantic_role:event_mention, candidate_family..."

Layer 3 relation candidates

,candidate_id,canonical_label,mentions,controlled_hints
0,cand_r_00000,PRECONDITION,[S1[2:4]::checks into || enables || S3[39:40]:...,[controlled_relation:PRECONDITION]
1,cand_r_00001,PRECONDITION,[S3[1:2]::skipping || enables || S1[2:4]::chec...,[controlled_relation:PRECONDITION]
2,cand_r_00002,PRECONDITION,[S3[4:5]::entering || enables || S1[2:4]::chec...,[controlled_relation:PRECONDITION]
3,cand_r_00003,PRECONDITION,[S3[11:12]::facing || motivates || S1[2:4]::ch...,[controlled_relation:PRECONDITION]
4,cand_r_00004,PRECONDITION,[S3[15:16]::arrest || enables || S3[24:26]::ch...,[controlled_relation:PRECONDITION]
5,cand_r_00005,PRECONDITION,[S3[17:18]::violating || enables || S3[15:16]:...,[controlled_relation:PRECONDITION]
6,cand_r_00006,PRECONDITION,[S3[17:18]::violating || enables || S3[24:26]:...,[controlled_relation:PRECONDITION]
7,cand_r_00007,PRECONDITION,[S3[24:26]::checked into || enables || S3[31:3...,[controlled_relation:PRECONDITION]
8,cand_r_00008,FALLING_ACTION,[S5[6:7]::comes || comes after || S3[24:26]::c...,[controlled_relation:FALLING_ACTION]
9,cand_r_00009,PRECONDITION,[S5[6:7]::comes || comes after || S3[31:32]::b...,[controlled_relation:PRECONDITION]
10,cand_r_00010,S5[6:7]::comes || comes after || S3[39:40]::stay,[S5[6:7]::comes || comes after || S3[39:40]::s...,[]
11,cand_r_00011,PRECONDITION,[S5[6:7]::comes || comes after || S3[44:45]::c...,[controlled_relation:PRECONDITION]
12,cand_r_00012,PRECONDITION,[S5[9:12]::rear - ended || rear‑ended || S3[24...,[controlled_relation:PRECONDITION]
13,cand_r_00013,PRECONDITION,[S5[9:12]::rear - ended || rear‑ended || S3[31...,[controlled_relation:PRECONDITION]
14,cand_r_00014,FALLING_ACTION,[S5[9:12]::rear - ended || rear‑ended || S3[39...,[controlled_relation:FALLING_ACTION]
15,cand_r_00015,FALLING_ACTION,[S5[9:12]::rear - ended || rear‑ended || S3[44...,[controlled_relation:FALLING_ACTION]
16,cand_r_00016,PRECONDITION,[S5[27:28]::lied || lied || S3[24:26]::checked...,[controlled_relation:PRECONDITION]
17,cand_r_00017,PRECONDITION,[S5[27:28]::lied || lied || S3[31:32]::begin],[controlled_relation:PRECONDITION]
18,cand_r_00018,PRECONDITION,[S5[27:28]::lied || lied || S3[39:40]::stay],[controlled_relation:PRECONDITION]
19,cand_r_00019,PRECONDITION,[S5[27:28]::lied || lied || S3[44:45]::convict...,[controlled_relation:PRECONDITION]
20,cand_r_00020,PRECONDITION,[S5[31:32]::telling || telling || S3[24:26]::c...,[controlled_relation:PRECONDITION]
21,cand_r_00021,PRECONDITION,[S5[31:32]::telling || telling || S3[31:32]::b...,[controlled_relation:PRECONDITION]
22,cand_r_00022,PRECONDITION,[S5[31:32]::telling || telling || S3[39:40]::s...,[controlled_relation:PRECONDITION]
23,cand_r_00023,PRECONDITION,[S5[31:32]::telling || telling || S3[44:45]::c...,[controlled_relation:PRECONDITION]
24,cand_r_00024,FALLING_ACTION,[S5[34:37]::was not driving || after || S3[39:...,[controlled_relation:FALLING_ACTION]
25,cand_r_00025,PRECONDITION,[S5[36:37]::driving || after || S3[39:40]::stay],[controlled_relation:PRECONDITION]

Layer 4 assertions

,source,predicate,target,confidence
0,S1[2:4]::checks into,PRECONDITION,S3[39:40]::stay,1.0
1,S3[1:2]::skipping,PRECONDITION,S1[2:4]::checks into,1.0
2,S3[4:5]::entering,PRECONDITION,S1[2:4]::checks into,1.0
3,S3[11:12]::facing,PRECONDITION,S1[2:4]::checks into,1.0
4,S3[15:16]::arrest,PRECONDITION,S3[24:26]::checked into,1.0
5,S3[17:18]::violating,PRECONDITION,S3[15:16]::arrest,1.0
6,S3[17:18]::violating,PRECONDITION,S3[24:26]::checked into,1.0
7,S3[24:26]::checked into,PRECONDITION,S3[31:32]::begin,1.0
8,S5[6:7]::comes,FALLING_ACTION,S3[24:26]::checked into,1.0
9,S5[6:7]::comes,PRECONDITION,S3[31:32]::begin,1.0
10,S5[6:7]::comes,S5[6:7]::comes || comes after || S3[39:40]::stay,S3[39:40]::stay,1.0
11,S5[6:7]::comes,PRECONDITION,S3[44:45]::conviction,1.0
12,S5[9:12]::rear - ended,PRECONDITION,S3[24:26]::checked into,1.0
13,S5[9:12]::rear - ended,PRECONDITION,S3[31:32]::begin,1.0
14,S5[9:12]::rear - ended,FALLING_ACTION,S3[39:40]::stay,1.0
15,S5[9:12]::rear - ended,FALLING_ACTION,S3[44:45]::conviction,1.0
16,S5[27:28]::lied,PRECONDITION,S3[24:26]::checked into,1.0
17,S5[27:28]::lied,PRECONDITION,S3[31:32]::begin,1.0
18,S5[27:28]::lied,PRECONDITION,S3[39:40]::stay,1.0
19,S5[27:28]::lied,PRECONDITION,S3[44:45]::conviction,1.0
20,S5[31:32]::telling,PRECONDITION,S3[24:26]::checked into,1.0
21,S5[31:32]::telling,PRECONDITION,S3[31:32]::begin,1.0
22,S5[31:32]::telling,PRECONDITION,S3[39:40]::stay,1.0
23,S5[31:32]::telling,PRECONDITION,S3[44:45]::conviction,1.0
24,S5[34:37]::was not driving,FALLING_ACTION,S3[39:40]::stay,1.0
25,S5[36:37]::driving,PRECONDITION,S3[39:40]::stay,1.0

Layer 5 triples

,subject,predicate,object,confidence
0,S1[2:4]::checks into,PRECONDITION,S3[39:40]::stay,1.0
1,S3[1:2]::skipping,PRECONDITION,S1[2:4]::checks into,1.0
2,S3[4:5]::entering,PRECONDITION,S1[2:4]::checks into,1.0
3,S3[11:12]::facing,PRECONDITION,S1[2:4]::checks into,1.0
4,S3[15:16]::arrest,PRECONDITION,S3[24:26]::checked into,1.0
5,S3[17:18]::violating,PRECONDITION,S3[15:16]::arrest,1.0
6,S3[17:18]::violating,PRECONDITION,S3[24:26]::checked into,1.0
7,S3[24:26]::checked into,PRECONDITION,S3[31:32]::begin,1.0
8,S5[6:7]::comes,FALLING_ACTION,S3[24:26]::checked into,1.0
9,S5[6:7]::comes,PRECONDITION,S3[31:32]::begin,1.0
10,S5[6:7]::comes,S5[6:7]::comes || comes after || S3[39:40]::stay,S3[39:40]::stay,1.0
11,S5[6:7]::comes,PRECONDITION,S3[44:45]::conviction,1.0
12,S5[9:12]::rear - ended,PRECONDITION,S3[24:26]::checked into,1.0
13,S5[9:12]::rear - ended,PRECONDITION,S3[31:32]::begin,1.0
14,S5[9:12]::rear - ended,FALLING_ACTION,S3[39:40]::stay,1.0
15,S5[9:12]::rear - ended,FALLING_ACTION,S3[44:45]::conviction,1.0
16,S5[27:28]::lied,PRECONDITION,S3[24:26]::checked into,1.0
17,S5[27:28]::lied,PRECONDITION,S3[31:32]::begin,1.0
18,S5[27:28]::lied,PRECONDITION,S3[39:40]::stay,1.0
19,S5[27:28]::lied,PRECONDITION,S3[44:45]::conviction,1.0
20,S5[31:32]::telling,PRECONDITION,S3[24:26]::checked into,1.0
21,S5[31:32]::telling,PRECONDITION,S3[31:32]::begin,1.0
22,S5[31:32]::telling,PRECONDITION,S3[39:40]::stay,1.0
23,S5[31:32]::telling,PRECONDITION,S3[44:45]::conviction,1.0
24,S5[34:37]::was not driving,FALLING_ACTION,S3[39:40]::stay,1.0
25,S5[36:37]::driving,PRECONDITION,S3[39:40]::stay,1.0

Layer 6 ontology relation candidates: 3
Layer 11 completion candidates: 0

## 9. Event projection audit

In [11]:
projection = pd.read_csv(RUN_DIR / "analysis/event_projection_audit.csv")
display(projection)

# Exact-span demonstration using source structure. Gold is consulted only here,
# after the pipeline has completed.
first_gold_key = next(iter(gold_event_index(gold)["keys_by_id"].values()))[0]
print(first_gold_key)
print(project_event_label(first_gold_key, gold))

,event_id,method,label,candidate_event_ids
0,EVENT_34cccabacad4dea93d3e762114dc05cd,exact_sentence_token_span,S1[2:4]::checks into,NaN
1,NaN,unmapped_or_ambiguous,S3[1:2]::skipping,[]
2,EVENT_b79df11f8737f700691af4f8a7132190,exact_sentence_token_span,S3[4:5]::entering,NaN
3,NaN,unmapped_or_ambiguous,S3[11:12]::facing,[]
4,EVENT_c332a6b60af0495f34856f112dc68632,exact_sentence_token_span,S3[15:16]::arrest,NaN
5,EVENT_9c07ef70f303f23dd82b32fb28a61ecb,exact_sentence_token_span,S3[17:18]::violating,NaN
6,EVENT_d7aec1e4ff20c3264f9fb7686355eb8a,exact_sentence_token_span,S3[24:26]::checked into,NaN
7,NaN,unmapped_or_ambiguous,S3[31:32]::begin,[]
8,EVENT_2ea9a901cc230afcc371bcffee02a551,exact_sentence_token_span,S3[39:40]::stay,NaN
9,EVENT_7d29e127b36f34a94ceb0f13f9ea3a3b,exact_sentence_token_span,S3[44:45]::conviction,NaN
10,EVENT_434faad0c9ec71baa6a91df3c385299b,exact_sentence_token_span,S4[15:16]::violation,NaN
11,EVENT_89d0247006cb23119f629915dbc5aec7,globally_unique_trigger,S4[20:21]::driving,NaN
12,NaN,unmapped_or_ambiguous,S5[6:7]::comes,[]
13,EVENT_401ce8fe35db27ca7b5f7cf83acc4084,exact_sentence_token_span,S5[9:12]::rear - ended,NaN
14,EVENT_a8934f381d6d835057ba8c537386ff9e,exact_sentence_token_span,S5[27:28]::lied,NaN
15,EVENT_f83b48c549abe22d26dc21624d8de397,exact_sentence_token_span,S5[31:32]::telling,NaN
16,NaN,unmapped_or_ambiguous,S5[34:37]::was not driving,[]
17,EVENT_89d0247006cb23119f629915dbc5aec7,exact_sentence_token_span,S5[36:37]::driving,NaN

S4[15:16]::violation
{'event_id': 'EVENT_434faad0c9ec71baa6a91df3c385299b', 'method': 'exact_sentence_token_span', 'label': 'S4[15:16]::violation'}

## 10. Speed, concurrency and errors

In [12]:
def optional_jsonl(path: Path) -> pd.DataFrame:
    return pd.DataFrame(read_jsonl(path)) if path.is_file() else pd.DataFrame()

calls = optional_jsonl(RUN_DIR / "run_logs/llm_calls.jsonl")
errors = optional_jsonl(RUN_DIR / "run_logs/llm_errors.jsonl")
parse_errors = optional_jsonl(RUN_DIR / "run_logs/llm_parse_errors.jsonl")
retrieval = optional_jsonl(RUN_DIR / "run_logs/ontology_retrieval.jsonl")

if not calls.empty:
    display(calls)
    display(calls.groupby("layer_tag").agg(
        calls=("call_index", "count"),
        total_recorded_seconds=("elapsed_seconds", "sum"),
        maximum_call_seconds=("elapsed_seconds", "max"),
        mean_system_chars=("system_chars", "mean"),
        mean_user_chars=("user_chars", "mean"),
        mean_response_chars=("response_chars", "mean"),
    ).reset_index())

print("Backend/API errors:", len(errors))
if not errors.empty: display(errors)
print("JSON parse errors:", len(parse_errors))
if not parse_errors.empty: display(parse_errors)
if not retrieval.empty:
    display(retrieval.groupby("layer_name").size().reset_index(name="retrieval_calls"))

manifest = read_json(RUN_DIR / "run_manifest.json")
print("Wall-clock pipeline seconds:", manifest.get("elapsed_seconds"))

,call_index,layer_tag,model,temperature,message_count,system_chars,user_chars,max_tokens,request_timeout,started_at,status,elapsed_seconds,response_chars,response_path,json_parse_ok,parsed_type,parse_error
0,3,layer01_event_instances,openai/gpt-oss-20b,0.0,2,1264,2756,8192,180,2026-07-31 01:38:40,ok,3.764,350,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
1,2,layer01_event_instances,openai/gpt-oss-20b,0.0,2,1264,3097,8192,180,2026-07-31 01:38:40,ok,6.145,1101,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
2,1,layer01_event_instances,openai/gpt-oss-20b,0.0,2,1264,2537,8192,180,2026-07-31 01:38:40,ok,21.209,199,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
3,4,layer01_event_instances,openai/gpt-oss-20b,0.0,2,1264,2907,8192,180,2026-07-31 01:38:40,ok,41.486,804,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
4,5,layer01_event_instances,openai/gpt-oss-20b,0.0,2,995,9621,8192,180,2026-07-31 01:39:21,ok,68.561,208,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
5,6,layer01_event_instances,openai/gpt-oss-20b,0.0,2,1064,9621,8192,180,2026-07-31 01:40:30,ok,40.274,420,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
6,8,layer01_event_instances,openai/gpt-oss-20b,0.0,2,1336,8995,8192,180,2026-07-31 01:41:10,ok,3.202,797,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
7,11,layer01_event_instances,openai/gpt-oss-20b,0.0,2,1336,8977,8192,180,2026-07-31 01:41:10,ok,3.702,515,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
8,9,layer01_event_instances,openai/gpt-oss-20b,0.0,2,1336,8995,8192,180,2026-07-31 01:41:10,ok,5.024,629,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
9,10,layer01_event_instances,openai/gpt-oss-20b,0.0,2,1336,8995,8192,180,2026-07-31 01:41:10,ok,9.768,2703,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
10,7,layer01_event_instances,openai/gpt-oss-20b,0.0,2,1336,8995,8192,180,2026-07-31 01:41:10,ok,20.224,786,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
11,15,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4003,384,60,2026-07-31 01:41:30,ok,0.860,188,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
12,16,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,5016,384,60,2026-07-31 01:41:30,ok,1.119,167,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
13,13,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,5025,384,60,2026-07-31 01:41:30,ok,1.148,213,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
14,18,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,5035,384,60,2026-07-31 01:41:30,ok,1.158,145,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
15,19,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,5027,384,60,2026-07-31 01:41:30,ok,1.264,234,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
16,25,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4467,384,60,2026-07-31 01:41:30,ok,1.367,199,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
17,12,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,5007,384,60,2026-07-31 01:41:30,ok,1.493,242,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
18,26,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4460,384,60,2026-07-31 01:41:30,ok,1.445,184,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
19,29,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4573,384,60,2026-07-31 01:41:32,ok,0.526,182,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
20,27,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4507,384,60,2026-07-31 01:41:30,ok,1.727,221,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
21,14,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,5036,384,60,2026-07-31 01:41:30,ok,1.767,185,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
22,24,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4499,384,60,2026-07-31 01:41:30,ok,1.789,214,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
23,28,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4594,384,60,2026-07-31 01:41:31,ok,0.996,143,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
24,32,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4975,384,60,2026-07-31 01:41:32,ok,1.422,221,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
25,30,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4566,384,60,2026-07-31 01:41:32,ok,2.324,173,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
26,34,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4946,384,60,2026-07-31 01:41:32,ok,2.052,171,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
27,37,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4249,384,60,2026-07-31 01:41:32,ok,2.854,212,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
28,35,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4970,384,60,2026-07-31 01:41:32,ok,9.354,176,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
29,23,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4534,384,60,2026-07-31 01:41:30,ok,12.200,169,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
30,31,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4590,384,60,2026-07-31 01:41:32,ok,11.535,205,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
31,22,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4532,384,60,2026-07-31 01:41:30,ok,13.284,174,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
32,21,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4526,384,60,2026-07-31 01:41:30,ok,14.201,162,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
33,33,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4953,384,60,2026-07-31 01:41:32,ok,13.163,131,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
34,20,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4544,384,60,2026-07-31 01:41:30,ok,15.458,202,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
35,17,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,5011,384,60,2026-07-31 01:41:30,ok,29.687,128,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None
36,36,layer02_event_relation_linking,openai/gpt-oss-20b,0.0,2,955,4253,384,60,2026-07-31 01:41:32,ok,30.989,201,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...,True,dict,None

,layer_tag,calls,total_recorded_seconds,maximum_call_seconds,mean_system_chars,mean_user_chars,mean_response_chars
0,layer01_event_instances,11,223.359,68.561,1254.090909,6863.272727,773.818182
1,layer02_event_relation_linking,26,175.182,30.989,955.000000,4688.384615,186.230769

Backend/API errors: 0
JSON parse errors: 0

                     layer_name  retrieval_calls
0  layer02_candidate_enrichment               26

Wall-clock pipeline seconds: 203.571

## Success checklist before the five-document batch

1. The sibling RAGTree OWL-Time file resolves.
2. Parallel sentence extraction plus two whole-document reviews materially improves exact event recall.
3. Repeated mentions, eventive nominals, states, phrasal verbs, and hyphenated triggers retain exact indexed spans.
4. Layer 1B covers all validated sources in bounded batches and creates only closed-inventory pairs.
5. Layer 2 selects only `PRECONDITION`, `FALLING_ACTION`, or `found=false`; Layer 4 preserves direction.
6. Gold remains unavailable until post-Layer-12 evaluation. Freeze v1.3 before smoke-5 tuning.