# Native NeoOLAF DocRED **dev-only** streaming batch and evaluation — v6.2

This notebook keeps the frozen **v5.1 scientific configuration and evaluator**, but changes the batch orchestration so that:

- only records whose literal JSON key `"type"` equals `"dev"` are selected;
- the JSONL is scanned line by line instead of loaded into memory;
- no list containing all dev documents is constructed;
- at most `DOCUMENT_WORKERS` document jobs are submitted at once;
- the existing `LAYER_WORKERS` parallelism is retained inside each document;
- evaluation is rebuilt by streaming the per-document result files.

The intended workflow is:

1. leave `RUN_ALL_DEV_DOCUMENTS = False` and run the first five `type="dev"` records;
2. inspect the same strict DocRED relation/entity evaluation used previously;
3. change only `RUN_ALL_DEV_DOCUMENTS = True`;
4. rerun the configuration, preflight, and batch cells.

Completed runs under this notebook's batch root are resumed. Gold entities and relations are removed before each native NeoOLAF run and loaded only afterward for evaluation.

## Memory behavior

The parent process keeps only:

- the current JSONL line;
- at most `DOCUMENT_WORKERS` prepared/submitted jobs;
- small aggregate counters for 96 relation types and 13 layers.

Input/gold records and NeoOLAF artifacts are written to disk per document. The complete dev split is never materialized as a Python list or submitted to `ProcessPoolExecutor` all at once.

In [1]:
from __future__ import annotations

import os
import sys
import multiprocessing as mp
from getpass import getpass
from pathlib import Path

import pandas as pd
from IPython.display import display, Markdown


def find_project_root() -> Path:
    current = Path.cwd().resolve()
    for candidate in [current, *current.parents]:
        if (candidate / "pyproject.toml").is_file() and (candidate / "src/neoolaf").is_dir():
            return candidate
    raise FileNotFoundError("Run this notebook from inside the NeoOLAF repository.")


def first_existing_path(label: str, candidates: list[Path]) -> Path:
    checked = []
    for candidate in candidates:
        candidate = candidate.expanduser()
        candidate = candidate if candidate.is_absolute() else PROJECT_ROOT / candidate
        candidate = candidate.resolve()
        checked.append(candidate)
        if candidate.is_file():
            print(f"{label}={candidate}")
            return candidate
    raise FileNotFoundError(
        f"Could not find {label}. Checked:\n" + "\n".join(str(path) for path in checked)
    )


PROJECT_ROOT = find_project_root()
NOTEBOOK_DIR = PROJECT_ROOT / "examples/RAGTreeDatasets"
TOOLS_DIR = NOTEBOOK_DIR / "tools"
for path in [PROJECT_ROOT / "src", PROJECT_ROOT, TOOLS_DIR]:
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from docred_native_batch_v6_2_dev_streaming import (
    BatchRunConfig,
    aggregate_batch_results_streaming,
    count_exact_type_records,
    read_json,
    run_batch_streaming,
)

mp.freeze_support()
print("PROJECT_ROOT =", PROJECT_ROOT)

PROJECT_ROOT = /home/galencarmedeiro/git/postdoc/NeoOLAF

/home/galencarmedeiro/git/postdoc/NeoOLAF/.venv/lib/python3.12/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.2.0)/charset_normalizer (3.4.6) doesn't match a supported version!
  warnings.warn(
/home/galencarmedeiro/git/postdoc/NeoOLAF/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Exact `type="dev"` filter and one-variable smoke/full switch

In [2]:
# Change only this variable after the five-document dev smoke run succeeds.
RUN_ALL_DEV_DOCUMENTS = True

# Used only while RUN_ALL_DEV_DOCUMENTS=False.
SMOKE_DEV_DOCUMENT_LIMIT = 5

# Index among matching type="dev" records. Keep 0 for the complete dev split.
START_DEV_INDEX = 0

# Frozen exact filter: it checks record["type"] only and does not fall back to "split".
EXACT_TYPE_VALUE = "dev"

DATASET_JSONL = first_existing_path(
    "DATASET_JSONL",
    [
        NOTEBOOK_DIR / "../../../ragtree/data/preprocessed/docred_causal.jsonl",
        PROJECT_ROOT.parent / "ragtree/data/preprocessed/docred_causal.jsonl",
        PROJECT_ROOT.parent / "RAGTree/data/preprocessed/docred_causal.jsonl",
        PROJECT_ROOT / "ragtree/data/preprocessed/docred_causal.jsonl",
    ],
)

# Separate root prevents collisions with the previous unfiltered five-document batch.
# Keep this same root when switching RUN_ALL_DEV_DOCUMENTS to True so smoke runs resume.
BATCH_ROOT = NOTEBOOK_DIR / "runs/docred_native_v5_1_dev_streaming"

print("RUN_ALL_DEV_DOCUMENTS =", RUN_ALL_DEV_DOCUMENTS)
print("DATASET_JSONL =", DATASET_JSONL)
print("BATCH_ROOT =", BATCH_ROOT)

DATASET_JSONL=/home/galencarmedeiro/git/postdoc/ragtree/data/preprocessed/docred_causal.jsonl
RUN_ALL_DEV_DOCUMENTS = True
DATASET_JSONL = /home/galencarmedeiro/git/postdoc/ragtree/data/preprocessed/docred_causal.jsonl
BATCH_ROOT = /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/runs/docred_native_v5_1_dev_streaming

## 2. Frozen v5.1 scientific configuration and parallel workers

In [3]:
ONTOLOGY_PATH = NOTEBOOK_DIR / "ontology/docred_redocred_neoolaf_compatible.ttl"
ONTOLOGY_ORIGINAL = NOTEBOOK_DIR / "ontology/docred_redocred_original.ttl"
RELATION_CATALOG = NOTEBOOK_DIR / "ontology/docred_relation_catalog.json"
RELATION_ALIASES = NOTEBOOK_DIR / "ontology/docred_relation_aliases.json"
PROFILE_PATH = NOTEBOOK_DIR / "configs/docred_profile_native_ablation_v5.json"
GUIDANCE_PATH = NOTEBOOK_DIR / "configs/guidance_docred_native_ablation_v5.json"
TASK_GUIDANCE_PATH = NOTEBOOK_DIR / "configs/docred_task_guidance_v5_1_frozen.json"

OPENROUTER_HOST = "https://openrouter.ai/api/v1"
MODEL_NAME = "openai/gpt-oss-20b"
API_KEY = os.environ.get("OPENROUTER_API_KEY", "").strip().strip('"').strip("'")

# Parallel NeoOLAF documents. The streaming scheduler holds no more than this many jobs.
DOCUMENT_WORKERS = 4

# Existing v5.1 parallel relation-enrichment workers inside each document.
LAYER_WORKERS = 16

REASONING_EFFORT = "minimal"
MAX_TOKENS = 4096
REQUEST_TIMEOUT = 120

RESUME_COMPLETED = True
RETRY_FAILED_DOCUMENTS = True
DOCUMENT_ATTEMPTS = 2
RETRY_BACKOFF_SECONDS = 8.0
DOCUMENT_LAUNCH_STAGGER_SECONDS = 0.75
VERBOSE_DOCUMENTS = False
PROGRESS_EVERY = 1 if not RUN_ALL_DEV_DOCUMENTS else 10

print("Document workers / maximum pending documents:", DOCUMENT_WORKERS)
print("Layer workers per document:", LAYER_WORKERS)
print("Maximum theoretical concurrent Layer 2 requests:", DOCUMENT_WORKERS * LAYER_WORKERS)
print("API key available:", bool(API_KEY))

Document workers / maximum pending documents: 4
Layer workers per document: 16
Maximum theoretical concurrent Layer 2 requests: 64
API key available: True

## 3. Streaming preflight and anti-leakage assertions

In [4]:
required = [
    DATASET_JSONL,
    ONTOLOGY_PATH,
    ONTOLOGY_ORIGINAL,
    RELATION_CATALOG,
    RELATION_ALIASES,
    PROFILE_PATH,
    GUIDANCE_PATH,
    TASK_GUIDANCE_PATH,
]
missing = [str(path) for path in required if not path.is_file()]
if missing:
    raise FileNotFoundError("Missing required files:\n" + "\n".join(missing))

profile = read_json(PROFILE_PATH)
task_guidance = read_json(TASK_GUIDANCE_PATH)
catalog = read_json(RELATION_CATALOG)

# One streaming scan: counts exact type="dev" records without retaining documents.
corpus_scan = count_exact_type_records(
    DATASET_JSONL,
    required_type=EXACT_TYPE_VALUE,
    first_n_ids=5,
)
matching_records = int(corpus_scan["matching_records"])
available_after_start = max(0, matching_records - START_DEV_INDEX)
selected_count = (
    available_after_start
    if RUN_ALL_DEV_DOCUMENTS
    else min(SMOKE_DEV_DOCUMENT_LIMIT, available_after_start)
)

print("JSONL records:", corpus_scan["total_records"])
print('Records with exact key/value type="dev":', matching_records)
print("Selected this invocation:", selected_count)
print("First matching dev IDs:", corpus_scan["first_matching_ids"])
print("Ontology properties:", catalog["property_count"])
print("Allowed relation IDs:", len(task_guidance["allowed_relation_ids"]))
print("Frozen profile:", profile["profile_name"])

assert EXACT_TYPE_VALUE == "dev"
assert catalog["property_count"] == 96
assert len(task_guidance["allowed_relation_ids"]) == 96
assert profile["relations"]["allowed"] == []
assert profile["anti_cheating"]["direct_docred_extraction"] is False
assert profile["anti_cheating"]["source_entity_anchoring"] is False
assert profile["anti_cheating"]["post_run_relation_invention"] is False
assert profile["benchmark_projection"]["gold_available_to_pipeline"] is False
assert 3 <= DOCUMENT_WORKERS <= 5
assert selected_count > 0

display(Markdown(
    f"**Mode:** {'all exact type=dev documents' if RUN_ALL_DEV_DOCUMENTS else 'first five exact type=dev documents'}  \n"
    f"**Selected:** {selected_count} of {matching_records} dev documents  \n"
    f"**Parent memory bound:** at most {DOCUMENT_WORKERS} submitted document jobs  \n"
    f"**Resume:** {RESUME_COMPLETED}; keep the same batch root when switching to all dev documents."
))

JSONL records: 106924
Records with exact key/value type="dev": 998
Selected this invocation: 998
First matching dev IDs: ['DocRED - e37288ca6012859f', 'DocRED - 72971f0f36693b3a', 'DocRED - 0af496a208c087f2', 'DocRED - 3b611c48af52425e', 'DocRED - 2d3e5aaa2e9e3e9b']
Ontology properties: 96
Allowed relation IDs: 96
Frozen profile: docred_native_country_compact_ablation_v5

**Mode:** all exact type=dev documents
**Selected:** 998 of 998 dev documents
**Parent memory bound:** at most 4 submitted document jobs
**Resume:** True; keep the same batch root when switching to all dev documents.

## 4. Run native NeoOLAF with bounded document streaming

The launcher reads the JSONL iteratively and advances to another `type="dev"` record only after a document-worker slot is available. It does not prepare all dev records or submit all futures in advance.

Each selected document still receives its complete Layer 0–12 run, logs, prompts, raw responses, ontology artifacts, strict relation evaluation, entity evaluation, and cumulative layer analysis.

In [5]:
RUN_PIPELINE = True

if RUN_PIPELINE:
    if not API_KEY:
        API_KEY = getpass("OpenRouter API key: ").strip().strip('"').strip("'")
    if not API_KEY:
        raise RuntimeError("No OpenRouter API key was provided.")

    config = BatchRunConfig(
        project_root=str(PROJECT_ROOT),
        ontology_path=str(ONTOLOGY_PATH),
        profile_path=str(PROFILE_PATH),
        guidance_path=str(GUIDANCE_PATH),
        relation_catalog_path=str(RELATION_CATALOG),
        relation_aliases_path=str(RELATION_ALIASES),
        model_name=MODEL_NAME,
        host=OPENROUTER_HOST,
        document_workers=DOCUMENT_WORKERS,
        layer_workers=LAYER_WORKERS,
        reasoning_effort=REASONING_EFFORT,
        max_tokens=MAX_TOKENS,
        request_timeout=REQUEST_TIMEOUT,
        resume_completed=RESUME_COMPLETED,
        retry_failed_documents=RETRY_FAILED_DOCUMENTS,
        document_attempts=DOCUMENT_ATTEMPTS,
        retry_backoff_seconds=RETRY_BACKOFF_SECONDS,
        launch_stagger_seconds=DOCUMENT_LAUNCH_STAGGER_SECONDS,
        verbose_documents=VERBOSE_DOCUMENTS,
        progress_every=PROGRESS_EVERY,
    )

    batch = run_batch_streaming(
        dataset_jsonl=DATASET_JSONL,
        task_guidance_path=TASK_GUIDANCE_PATH,
        batch_root=BATCH_ROOT,
        run_all_documents=RUN_ALL_DEV_DOCUMENTS,
        smoke_document_limit=SMOKE_DEV_DOCUMENT_LIMIT,
        start_index=START_DEV_INDEX,
        config=config,
        api_key=API_KEY,
        matching_record_count=matching_records,
        required_type=EXACT_TYPE_VALUE,
    )
    print("Dev-only bounded streaming execution and aggregate evaluation completed.")
else:
    batch = aggregate_batch_results_streaming(
        batch_root=BATCH_ROOT,
        relation_catalog_path=RELATION_CATALOG,
    )
    print("RUN_PIPELINE=False: aggregate evaluation rebuilt iteratively from saved document files.")

[1/998] skipped_completed: DocRED - e37288ca6012859f | pipeline=20.073s

/home/galencarmedeiro/git/postdoc/NeoOLAF/.venv/lib/python3.12/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.2.0)/charset_normalizer (3.4.6) doesn't match a supported version!
  warnings.warn(
/home/galencarmedeiro/git/postdoc/NeoOLAF/.venv/lib/python3.12/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.2.0)/charset_normalizer (3.4.6) doesn't match a supported version!
  warnings.warn(
/home/galencarmedeiro/git/postdoc/NeoOLAF/.venv/lib/python3.12/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.2.0)/charset_normalizer (3.4.6) doesn't match a supported version!
  warnings.warn(
/home/galencarmedeiro/git/postdoc/NeoOLAF/.venv/lib/python3.12/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.2.0)/charset_normalizer (3.4.6) doesn't match a supported version!
  warnings.warn(

[10/998] completed: DocRED - 870d7d51388dd9c2 | pipeline=19.937s
[20/998] completed: DocRED - 1fe77c1886347cbb | pipeline=22.689s
[30/998] completed: DocRED - 376edafcd90c34f5 | pipeline=9.889s
[40/998] completed: DocRED - 865910b4761a8421 | pipeline=33.804s
[50/998] completed: DocRED - b575ebc1a539a591 | pipeline=23.559s
[60/998] completed: DocRED - d19f7b9f0509c1d2 | pipeline=11.831s
[70/998] completed: DocRED - 17b763e5945e3e10 | pipeline=25.136s
[80/998] completed: DocRED - ce6fe4fce2c8e9e3 | pipeline=0.989s
[90/998] completed: DocRED - 0ded5069fa77eb8b | pipeline=19.099s
[100/998] completed: DocRED - a98bdb34b2d7dd03 | pipeline=8.01s
[110/998] completed: DocRED - 791a4f4a6ac77472 | pipeline=8.383s
[120/998] completed: DocRED - 4db636c8ac36eec5 | pipeline=19.319s
[130/998] completed: DocRED - 4fff93af17cde36a | pipeline=13.806s
[140/998] completed: DocRED - 07c5152a92b5e0bc | pipeline=9.571s
[150/998] completed: DocRED - bd9d38a525c44235 | pipeline=17.801s
[160/998] completed: DocRED - ed2def36fbbe460b | pipeline=10.131s
[170/998] completed: DocRED - 39e574424a501d33 | pipeline=9.052s
[180/998] completed: DocRED - 75a50ca6749b1486 | pipeline=26.949s
[181/998] failed: DocRED - 41d762b7738a6d38 | pipeline=n/a | RuntimeError: No final message.content returned by backend openrouter. This is not an API-key/credits error: the request returned choices, but the final assistant content was empty. For OpenRouter reasoning models, try --max-tokens 8192 --openrouter-reasoning-effort minimal --openrouter-exclude-reasoning. Backend debug: {'id': 'gen-1784776923-4LsNHKeMfhqngF5B4PD4', 'model': 'openai/gpt-oss-20b', 'provider': 'SiliconFlow', 'finish_reason': None, 'native_finish_reason': None, 'message_keys': ['content', 'refusal', 'role'], 'content_is_none': True, 'content_len': 0, 'has_reasoning': False, 'reasoning_len': 0, 'has_reasoning_details': False, 'usage': {'prompt_tokens': 1564, 'completion_tokens': 1606, 'total_tokens': 3170, 'cost': 0.00035164, 'is_byok': False, 'prompt_tokens_details': {'cached_tokens': 0, 'cache_write_tokens': 0, 'audio_tokens': 0, 'video_tokens': 0}, 'cost_details': {'upstream_inference_cost': 0.00035164, 'upstream_inference_prompt_cost': 6.256e-05, 'upstream_inference_completions_cost': 0.00028908}, 'completion_tokens_details': {'reasoning_tokens': 1606, 'image_tokens': 0, 'audio_tokens': 0}}} | transient=False
[190/998] completed: DocRED - 00698a048ae365ce | pipeline=29.33s
[200/998] completed: DocRED - 38e073cd3d4151ba | pipeline=15.736s
[210/998] completed: DocRED - fa0dcea926f34584 | pipeline=13.595s
[220/998] completed: DocRED - 4a1260969c670c79 | pipeline=26.908s
[230/998] completed: DocRED - 631f41ddf7e76708 | pipeline=13.66s
[240/998] completed: DocRED - 0ce5b30b1e4f4538 | pipeline=23.563s
[250/998] completed: DocRED - 391f83935d9cb644 | pipeline=4.186s
[260/998] completed: DocRED - 691b2d30f7363921 | pipeline=20.691s
[270/998] completed: DocRED - 646c8a985413286d | pipeline=10.598s
[280/998] completed: DocRED - b5137ffa781c4c91 | pipeline=13.733s
[290/998] completed: DocRED - 957e341377864f63 | pipeline=24.761s
[300/998] completed: DocRED - 2358e66849910c56 | pipeline=4.647s
[310/998] completed: DocRED - 3913f53382fc94bb | pipeline=4.288s
[320/998] completed: DocRED - f57080e28a806324 | pipeline=8.803s
[330/998] completed: DocRED - 995ee7c5ba39626c | pipeline=8.167s
[340/998] completed: DocRED - 700c54e24807294b | pipeline=22.272s
[350/998] completed: DocRED - 8d58057a6ce21b5f | pipeline=30.562s
[360/998] completed: DocRED - d8793625dffb07b3 | pipeline=11.839s
[370/998] completed: DocRED - 58b981802268fb80 | pipeline=27.136s
[380/998] completed: DocRED - 0716123d74880e1c | pipeline=5.562s
[387/998] failed: DocRED - d5afb4f79b8f78bf | pipeline=n/a | IndexError: list index out of range | transient=False
[390/998] completed: DocRED - 5a09d838fd3ef7a0 | pipeline=6.172s
[400/998] completed: DocRED - 38c73834ad624ab2 | pipeline=9.286s
[410/998] completed: DocRED - 25bfac7375f65179 | pipeline=21.397s
[414/998] failed: DocRED - cf134da0ca9d513b | pipeline=n/a | IndexError: list index out of range | transient=False
[420/998] failed: DocRED - f1c3a9b6567acdea | pipeline=n/a | IndexError: list index out of range | transient=False
[430/998] completed: DocRED - 561147ed067adfb4 | pipeline=3.715s
[440/998] completed: DocRED - ab7a3fdf90fcba89 | pipeline=1.397s
[450/998] completed: DocRED - d6995f63ac32ebd8 | pipeline=2.054s
[457/998] failed: DocRED - 2e2db7fa57b135a2 | pipeline=n/a | RuntimeError: layer01_country_aware: response length 29639 exceeds hard cap 26000; retrying with the same native task. | transient=False
[460/998] completed: DocRED - 2c0b53cf4af2fd27 | pipeline=33.568s
[470/998] completed: DocRED - f805c298665a6082 | pipeline=0.537s
[480/998] completed: DocRED - 95144260d697c664 | pipeline=3.729s
[481/998] failed: DocRED - aeb35b88a907b67f | pipeline=n/a | IndexError: list index out of range | transient=False
[490/998] completed: DocRED - cb4b66963b42a77a | pipeline=2.682s
[500/998] completed: DocRED - c544feba07239b7b | pipeline=1.931s
[506/998] failed: DocRED - 63e458d75bdcdc0b | pipeline=n/a | IndexError: list index out of range | transient=False
[510/998] completed: DocRED - 1aa0e78dd31294e6 | pipeline=2.307s
[520/998] completed: DocRED - 412edf9d946d53c0 | pipeline=2.365s
[523/998] failed: DocRED - d496f3bf42d98809 | pipeline=n/a | RuntimeError: No final message.content returned by backend openrouter. This is not an API-key/credits error: the request returned choices, but the final assistant content was empty. For OpenRouter reasoning models, try --max-tokens 8192 --openrouter-reasoning-effort minimal --openrouter-exclude-reasoning. Backend debug: {'id': 'gen-1784778972-kpTPXJgQsa9HwZrhtdRe', 'model': 'openai/gpt-oss-20b', 'provider': 'Groq', 'finish_reason': 'length', 'native_finish_reason': 'length', 'message_keys': ['content', 'refusal', 'role'], 'content_is_none': True, 'content_len': 0, 'has_reasoning': False, 'reasoning_len': 0, 'has_reasoning_details': False, 'usage': {'prompt_tokens': 1583, 'completion_tokens': 4096, 'total_tokens': 5679, 'cost': 0.001299525, 'is_byok': False, 'prompt_tokens_details': {'cached_tokens': 1280, 'cache_write_tokens': 0, 'audio_tokens': 0, 'video_tokens': 0}, 'cost_details': {'upstream_inference_cost': 0.001299525, 'upstream_inference_prompt_cost': 7.0725e-05, 'upstream_inference_completions_cost': 0.0012288}, 'completion_tokens_details': {'reasoning_tokens': 4094, 'image_tokens': 0, 'audio_tokens': 0}}} | transient=False
[529/998] failed: DocRED - 753581dbb1e75a38 | pipeline=n/a | IndexError: list index out of range | transient=False
[530/998] completed: DocRED - e9bdf60a46531d0b | pipeline=15.318s
[536/998] failed: DocRED - 34443841a446b053 | pipeline=n/a | IndexError: list index out of range | transient=False
[540/998] completed: DocRED - 7c234ed3cdb030e0 | pipeline=12.498s
[550/998] completed: DocRED - 34b7150b652f769c | pipeline=4.227s
[560/998] completed: DocRED - e5374eaa9709eb1d | pipeline=2.481s
[570/998] failed: DocRED - 1a1ae5bd9653f3a2 | pipeline=n/a | IndexError: list index out of range | transient=False
[580/998] completed: DocRED - 50f111c71091c2a3 | pipeline=17.291s
[587/998] failed: DocRED - 98e4c77830e81d00 | pipeline=n/a | RuntimeError: No final message.content returned by backend openrouter. This is not an API-key/credits error: the request returned choices, but the final assistant content was empty. For OpenRouter reasoning models, try --max-tokens 8192 --openrouter-reasoning-effort minimal --openrouter-exclude-reasoning. Backend debug: {'id': 'gen-1784779215-FWHDcp4neWoOWa00SUj0', 'model': 'openai/gpt-oss-20b', 'provider': 'Groq', 'finish_reason': 'length', 'native_finish_reason': 'length', 'message_keys': ['content', 'refusal', 'role'], 'content_is_none': True, 'content_len': 0, 'has_reasoning': False, 'reasoning_len': 0, 'has_reasoning_details': False, 'usage': {'prompt_tokens': 1825, 'completion_tokens': 4096, 'total_tokens': 5921, 'cost': 0.001317675, 'is_byok': False, 'prompt_tokens_details': {'cached_tokens': 1280, 'cache_write_tokens': 0, 'audio_tokens': 0, 'video_tokens': 0}, 'cost_details': {'upstream_inference_cost': 0.001317675, 'upstream_inference_prompt_cost': 8.8875e-05, 'upstream_inference_completions_cost': 0.0012288}, 'completion_tokens_details': {'reasoning_tokens': 4094, 'image_tokens': 0, 'audio_tokens': 0}}} | transient=False
[590/998] completed: DocRED - 91d26f331bd02018 | pipeline=1.509s
[600/998] completed: DocRED - 63c3382865d3fee9 | pipeline=2.543s
[610/998] completed: DocRED - 0cff5883eebcb70b | pipeline=20.39s
[620/998] completed: DocRED - a7a1dca35283779b | pipeline=4.527s
[630/998] completed: DocRED - 5897b47e99cd64bc | pipeline=27.547s
[640/998] completed: DocRED - 57a3bf311a6856c0 | pipeline=17.771s
[649/998] failed: DocRED - 96c4fbc14123ac9a | pipeline=n/a | RuntimeError: No final message.content returned by backend openrouter. This is not an API-key/credits error: the request returned choices, but the final assistant content was empty. For OpenRouter reasoning models, try --max-tokens 8192 --openrouter-reasoning-effort minimal --openrouter-exclude-reasoning. Backend debug: {'id': 'gen-1784779381-NDtvIulJRECD7vtT5wnA', 'model': 'openai/gpt-oss-20b', 'provider': 'Groq', 'finish_reason': 'length', 'native_finish_reason': 'length', 'message_keys': ['content', 'refusal', 'role'], 'content_is_none': True, 'content_len': 0, 'has_reasoning': False, 'reasoning_len': 0, 'has_reasoning_details': False, 'usage': {'prompt_tokens': 1695, 'completion_tokens': 4096, 'total_tokens': 5791, 'cost': 0.001307925, 'is_byok': False, 'prompt_tokens_details': {'cached_tokens': 1280, 'cache_write_tokens': 0, 'audio_tokens': 0, 'video_tokens': 0}, 'cost_details': {'upstream_inference_cost': 0.001307925, 'upstream_inference_prompt_cost': 7.9125e-05, 'upstream_inference_completions_cost': 0.0012288}, 'completion_tokens_details': {'reasoning_tokens': 4094, 'image_tokens': 0, 'audio_tokens': 0}}} | transient=False
[650/998] completed: DocRED - 27a38d2fc4849799 | pipeline=8.607s
[660/998] completed: DocRED - 868a0b5bf06e6b99 | pipeline=2.069s
[670/998] completed: DocRED - ddc8e436cc0b34b4 | pipeline=2.091s
[680/998] completed: DocRED - 5b1a74244e713471 | pipeline=5.954s
[690/998] completed: DocRED - 3c97585cd84673b0 | pipeline=18.12s
[700/998] completed: DocRED - 0f274672ec0eb7f5 | pipeline=6.338s
[710/998] completed: DocRED - 1d14174f2282e2ee | pipeline=18.931s
[720/998] completed: DocRED - 8f0139f653f7c4ff | pipeline=10.423s
[730/998] completed: DocRED - 272ed7ccf6c2b731 | pipeline=30.929s
[740/998] completed: DocRED - 57c19cf37cfec4e2 | pipeline=7.187s
[750/998] completed: DocRED - 553677a716f1fbd1 | pipeline=9.894s
[756/998] failed: DocRED - 41167d3897fd404f | pipeline=n/a | IndexError: list index out of range | transient=False
[760/998] completed: DocRED - b7bdad88ed0fd32b | pipeline=5.408s
[770/998] completed: DocRED - e5aaa8ee65fca71f | pipeline=12.935s
[780/998] completed: DocRED - 7b2592c5f955f137 | pipeline=39.594s
[790/998] completed: DocRED - 9c62064ab37a88b2 | pipeline=2.903s
[800/998] completed: DocRED - 9e66e952ff971a02 | pipeline=12.096s
[810/998] completed: DocRED - 328db19a9c009934 | pipeline=11.439s
[820/998] completed: DocRED - 62891d077db4fca0 | pipeline=25.537s
[830/998] completed: DocRED - bdf8b0d47ae0ea07 | pipeline=20.568s
[837/998] failed: DocRED - db2887e593e5e140 | pipeline=n/a | IndexError: list index out of range | transient=False
[840/998] completed: DocRED - a9588ea65098e62a | pipeline=52.89s
[848/998] failed: DocRED - 090a1f9e7d3030de | pipeline=n/a | IndexError: list index out of range | transient=False
[849/998] failed: DocRED - 5892bb8f26a1d5c2 | pipeline=n/a | RuntimeError: No final message.content returned by backend openrouter. This is not an API-key/credits error: the request returned choices, but the final assistant content was empty. For OpenRouter reasoning models, try --max-tokens 8192 --openrouter-reasoning-effort minimal --openrouter-exclude-reasoning. Backend debug: {'id': 'gen-1784780153-wwAzhCZ8qNVfrNY72lFJ', 'model': 'openai/gpt-oss-20b', 'provider': 'SiliconFlow', 'finish_reason': None, 'native_finish_reason': None, 'message_keys': ['content', 'refusal', 'role'], 'content_is_none': True, 'content_len': 0, 'has_reasoning': False, 'reasoning_len': 0, 'has_reasoning_details': False, 'usage': {'prompt_tokens': 1665, 'completion_tokens': 10118, 'total_tokens': 11783, 'cost': 0.00188784, 'is_byok': False, 'prompt_tokens_details': {'cached_tokens': 0, 'cache_write_tokens': 0, 'audio_tokens': 0, 'video_tokens': 0}, 'cost_details': {'upstream_inference_cost': 0.00188784, 'upstream_inference_prompt_cost': 6.66e-05, 'upstream_inference_completions_cost': 0.00182124}, 'completion_tokens_details': {'reasoning_tokens': 10118, 'image_tokens': 0, 'audio_tokens': 0}}} | transient=False
[850/998] completed: DocRED - e777c73ec365ed8e | pipeline=10.216s
[853/998] failed: DocRED - ff71412088fdd6fd | pipeline=n/a | IndexError: list index out of range | transient=False
[860/998] completed: DocRED - fc4b0881bdd6a441 | pipeline=17.695s
[870/998] completed: DocRED - b3d3a3a7f227e10d | pipeline=11.62s
[880/998] completed: DocRED - 1b484629e386a642 | pipeline=34.046s
[890/998] completed: DocRED - dec093874f8a81f6 | pipeline=9.179s
[900/998] completed: DocRED - 40d5ffe898143ccf | pipeline=25.226s
[910/998] completed: DocRED - 1280f63be7f64988 | pipeline=15.373s
[920/998] completed: DocRED - 6474725637a65bf7 | pipeline=2.343s
[930/998] completed: DocRED - 43aef96ed779ef19 | pipeline=2.368s
[940/998] completed: DocRED - 118e675037108062 | pipeline=215.799s
[945/998] failed: DocRED - e69e35c93312485e | pipeline=n/a | IndexError: list index out of range | transient=False
[950/998] completed: DocRED - 4448e22e322b4df6 | pipeline=14.534s
[960/998] completed: DocRED - 3ff079f9823a227a | pipeline=10.968s
[968/998] failed: DocRED - 4f132e289eeacc18 | pipeline=n/a | RuntimeError: No final message.content returned by backend openrouter. This is not an API-key/credits error: the request returned choices, but the final assistant content was empty. For OpenRouter reasoning models, try --max-tokens 8192 --openrouter-reasoning-effort minimal --openrouter-exclude-reasoning. Backend debug: {'id': 'gen-1784780842-vklX4qwTlfMXAdy0ykGM', 'model': 'openai/gpt-oss-20b', 'provider': 'SiliconFlow', 'finish_reason': None, 'native_finish_reason': None, 'message_keys': ['content', 'refusal', 'role'], 'content_is_none': True, 'content_len': 0, 'has_reasoning': False, 'reasoning_len': 0, 'has_reasoning_details': False, 'usage': {'prompt_tokens': 1658, 'completion_tokens': 10996, 'total_tokens': 12654, 'cost': 0.0020456, 'is_byok': False, 'prompt_tokens_details': {'cached_tokens': 0, 'cache_write_tokens': 0, 'audio_tokens': 0, 'video_tokens': 0}, 'cost_details': {'upstream_inference_cost': 0.0020456, 'upstream_inference_prompt_cost': 6.632e-05, 'upstream_inference_completions_cost': 0.00197928}, 'completion_tokens_details': {'reasoning_tokens': 10996, 'image_tokens': 0, 'audio_tokens': 0}}} | transient=False
[970/998] completed: DocRED - 800031b4a5f23789 | pipeline=9.233s
[980/998] completed: DocRED - 0477c30be29cd1c2 | pipeline=11.136s
[990/998] completed: DocRED - 9ec81248d4b73fd5 | pipeline=3.068s
[998/998] completed: DocRED - f9025fb638b930de | pipeline=23.031s
Dev-only bounded streaming execution and aggregate evaluation completed.

## 5. Aggregate relation and entity evaluation

In [6]:
summary = batch["summary"]
display(pd.DataFrame([{
    "documents_requested": summary["documents_requested"],
    "documents_completed_or_resumed": summary["documents_completed_or_resumed"],
    "documents_failed": summary["documents_failed"],
    "relation_micro_precision": summary["micro_relation"]["precision"],
    "relation_micro_recall": summary["micro_relation"]["recall"],
    "relation_micro_f1": summary["micro_relation"]["f1"],
    "relation_macro_precision": summary["macro_relation"]["precision"],
    "relation_macro_recall": summary["macro_relation"]["recall"],
    "relation_macro_f1": summary["macro_relation"]["f1"],
    "entity_micro_precision": summary["micro_entity_inventory"]["precision"],
    "entity_micro_recall": summary["micro_entity_inventory"]["recall"],
    "entity_micro_f1": summary["micro_entity_inventory"]["f1"],
    "endpoint_micro_precision": summary["micro_relation_endpoint_inventory"]["precision"],
    "endpoint_micro_recall": summary["micro_relation_endpoint_inventory"]["recall"],
    "endpoint_micro_f1": summary["micro_relation_endpoint_inventory"]["f1"],
    "mean_pipeline_seconds": summary["mean_document_pipeline_seconds"],
    "median_pipeline_seconds": summary["median_document_pipeline_seconds"],
}]))

print("First-failure counts across completed documents:")
display(pd.DataFrame(
    sorted(summary["first_failure_counts"].items(), key=lambda item: (-item[1], item[0])),
    columns=["first_failure", "gold_relations"],
))

,documents_requested,documents_completed_or_resumed,documents_failed,relation_micro_precision,relation_micro_recall,relation_micro_f1,relation_macro_precision,relation_macro_recall,relation_macro_f1,entity_micro_precision,entity_micro_recall,entity_micro_f1,endpoint_micro_precision,endpoint_micro_recall,endpoint_micro_f1,mean_pipeline_seconds,median_pipeline_seconds
0,998,978,20,0.433521,0.088494,0.146984,0.203505,0.090555,0.110263,1.0,0.50169,0.668167,0.738287,0.215055,0.333086,21.146232,12.977

First-failure counts across completed documents:

                                   first_failure  gold_relations
0      layer01_endpoint_missing_after_projection            6547
1              layer01_relation_instance_missing            4018
2                            survived_to_layer05            1045
3   layer02_wrong_or_missing_controlled_relation             530
4  layer04_endpoint_direction_or_type_validation              19

## 6. Per-document results (loaded from the streamed CSV)

In [7]:
per_document_path = Path(batch["paths"]["per_document_csv"])
per_document = pd.read_csv(per_document_path) if per_document_path.is_file() else pd.DataFrame()

if not per_document.empty:
    print("Completed documents in CSV:", len(per_document))
    print("Twenty-five lowest relation-F1 documents:")
    display(per_document.sort_values(
        ["relation_f1", "relation_recall", "relation_precision"],
        ascending=[True, True, True],
    ).head(25))
    display(per_document[[
        "relation_precision", "relation_recall", "relation_f1",
        "entity_precision", "entity_recall", "entity_f1",
        "pipeline_seconds",
    ]].describe())
else:
    print("No completed documents.")

Completed documents in CSV: 978
Twenty-five lowest relation-F1 documents:

,selection_index,source_index,document_id,title,status,pipeline_seconds,wall_seconds,relation_predicted,relation_gold,relation_tp,...,relation_precision,relation_recall,relation_f1,entity_precision,entity_recall,entity_f1,endpoint_precision,endpoint_recall,endpoint_f1,run_dir
6,6,6,DocRED - 870d7d51388dd9c2,Ned McEvoy,completed,19.937,20.631,0,25,0,...,0.0,0.0,0.0,1.0,0.200000,0.333333,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
9,9,9,DocRED - c7e20c1cd39660dc,Robert K. Huntington,completed,10.825,11.422,3,14,0,...,0.0,0.0,0.0,1.0,0.166667,0.285714,0.666667,0.166667,0.266667,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
10,10,10,DocRED - b7c1751749fd680d,More (The Sisters of Mercy song),completed,107.320,108.363,1,9,0,...,0.0,0.0,0.0,1.0,0.761905,0.864865,1.000000,0.200000,0.333333,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
11,11,11,DocRED - 6965789a3c1dcd11,Delaware General Assembly,completed,523.340,524.077,5,17,0,...,0.0,0.0,0.0,1.0,0.333333,0.500000,1.000000,0.750000,0.857143,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
13,13,13,DocRED - 410002886f5aaadc,Palestinian National Theatre,completed,5.981,6.599,0,3,0,...,0.0,0.0,0.0,1.0,0.846154,0.916667,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
15,15,15,DocRED - 66489d4a482b1768,Allen F. Moore,completed,10.429,11.055,0,30,0,...,0.0,0.0,0.0,1.0,0.387097,0.558140,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
16,16,16,DocRED - ac1cb5f651a13eb0,Johan Gottlieb Gahn,completed,23.007,23.760,0,7,0,...,0.0,0.0,0.0,1.0,0.500000,0.666667,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
17,17,17,DocRED - 73adc17de8216965,Siberia Governorate,completed,12.640,13.270,1,11,0,...,0.0,0.0,0.0,1.0,0.333333,0.500000,0.500000,0.142857,0.222222,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
18,18,18,DocRED - 0446f49b345ba71c,Quokka,completed,25.655,26.201,0,5,0,...,0.0,0.0,0.0,1.0,0.857143,0.923077,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
20,20,20,DocRED - ad28bc309b708830,Memogate (Pakistan),completed,4.853,5.355,0,9,0,...,0.0,0.0,0.0,1.0,0.095238,0.173913,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
23,23,23,DocRED - 6b507b3ce36b7b21,Julian Reinard,completed,2.076,2.685,0,8,0,...,0.0,0.0,0.0,1.0,0.692308,0.818182,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
25,25,25,DocRED - d0c238fb90143c55,Hooshang Seyhoun,completed,9.134,9.756,0,23,0,...,0.0,0.0,0.0,1.0,0.842105,0.914286,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
26,26,26,DocRED - 6d430a7b1ebea383,"Albemarle County, Virginia",completed,5.995,6.597,0,15,0,...,0.0,0.0,0.0,1.0,0.714286,0.833333,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
27,27,27,DocRED - 432a20db6c08b63f,Kurt Tucholsky,completed,31.576,32.192,1,8,0,...,0.0,0.0,0.0,1.0,0.555556,0.714286,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
29,29,29,DocRED - a3622e84a5ccf249,Addy Lee,completed,9.957,10.493,0,6,0,...,0.0,0.0,0.0,1.0,0.312500,0.476190,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
30,30,30,DocRED - f735fd3c7e7d98dc,Wilhelm Lanzky-Otto,completed,92.725,94.087,5,4,0,...,0.0,0.0,0.0,1.0,0.842105,0.914286,0.166667,0.200000,0.181818,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
32,32,32,DocRED - 97f9c13864d5a1db,(I Am) The Seeker,completed,25.175,26.085,1,7,0,...,0.0,0.0,0.0,1.0,0.722222,0.838710,0.500000,0.166667,0.250000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
33,33,33,DocRED - d1893c286967e516,Queen of Housewives,completed,26.089,26.732,0,18,0,...,0.0,0.0,0.0,1.0,0.187500,0.315789,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
35,35,35,DocRED - 4d09a625dac5937d,Grand Wing Servo-Tech,completed,53.192,53.670,0,9,0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
41,41,41,DocRED - ceead260a708ef88,America's Sweetheart (album),completed,27.116,27.660,0,20,0,...,0.0,0.0,0.0,1.0,0.629630,0.772727,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
42,42,42,DocRED - ad2cb96850a6bf2a,Brooks Pharmacy,completed,19.836,20.382,0,23,0,...,0.0,0.0,0.0,1.0,0.434783,0.606061,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
43,43,43,DocRED - dd7c10d9a5166de4,"Crouching Tiger, Hidden Dragon: Sword of Destiny",completed,3.471,4.001,0,19,0,...,0.0,0.0,0.0,1.0,0.185185,0.312500,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
44,44,44,DocRED - ec5014a06816a2c9,Bicycles &amp; Tricycles,completed,3.149,3.693,0,8,0,...,0.0,0.0,0.0,1.0,0.391304,0.562500,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
45,45,45,DocRED - 9e8ae2f2d595e5cc,Each Time You Break My Heart,completed,27.162,27.738,0,14,0,...,0.0,0.0,0.0,1.0,0.740741,0.851064,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
46,46,46,DocRED - 124de301d8f57ccb,UNESCO Confucius Prize for Literacy,completed,20.910,21.455,0,3,0,...,0.0,0.0,0.0,1.0,0.692308,0.818182,0.000000,0.000000,0.000000,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...

,relation_precision,relation_recall,relation_f1,entity_precision,entity_recall,entity_f1,pipeline_seconds
count,978.000000,978.000000,978.000000,978.000000,978.000000,978.000000,978.000000
mean,0.203505,0.090555,0.110263,0.972393,0.517329,0.647758,21.146232
std,0.320054,0.165373,0.182704,0.163929,0.232298,0.227416,55.549520
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.537000
25%,0.000000,0.000000,0.000000,1.000000,0.363636,0.533333,6.027500
50%,0.000000,0.000000,0.000000,1.000000,0.533333,0.695652,12.977000
75%,0.375000,0.125000,0.181818,1.000000,0.692308,0.818182,20.896500
max,1.000000,1.000000,0.937500,1.000000,1.000000,1.000000,858.986000

## 7. Per-relation micro evaluation

In [8]:
per_relation = pd.DataFrame(batch["per_relation"])
if not per_relation.empty:
    display(per_relation.sort_values(
        ["gold", "f1", "recall"],
        ascending=[False, True, True],
    ))
else:
    print("No relation metrics available.")

,relation_id,label,predicted,gold,true_positive,false_positive,false_negative,precision,recall,f1
27,P17,,1332,2779,777,555,2002,0.583333,0.279597,0.378010
9,P131,,275,1226,92,183,1134,0.334545,0.075041,0.122585
46,P27,,55,804,37,18,767,0.672727,0.046020,0.086147
20,P150,,0,608,0,0,608,0.000000,0.000000,0.000000
76,P577,,48,405,34,14,371,0.708333,0.083951,0.150110
...,...,...,...,...,...,...,...,...,...,...
84,P676,,0,8,0,0,8,0.000000,0.000000,0.000000
70,P551,,1,6,0,1,6,0.000000,0.000000,0.000000
92,P807,,7,2,0,7,2,0.000000,0.000000,0.000000
36,P190,,1,2,1,0,1,1.000000,0.500000,0.666667
6,P1198,,0,1,0,0,1,0.000000,0.000000,0.000000

## 8. Aggregate cumulative layer contribution

In [9]:
cumulative = pd.DataFrame(batch["cumulative"])
if not cumulative.empty:
    display(cumulative[[
        "layer_index", "layer_name", "predicted", "gold",
        "true_positive", "false_positive", "false_negative",
        "precision", "recall", "f1",
    ]])
else:
    print("No cumulative layer metrics available.")

,layer_index,layer_name,predicted,gold,true_positive,false_positive,false_negative,precision,recall,f1
0,0,layer00_preprocessing,0,12159,0,0,12159,0.000000,0.000000,0.000000
1,1,layer01_linguistic_expression_extraction,0,12159,0,0,12159,0.000000,0.000000,0.000000
2,2,layer02_candidate_enrichment,0,12159,0,0,12159,0.000000,0.000000,0.000000
3,3,layer03_candidate_typing_resolution,0,12159,0,0,12159,0.000000,0.000000,0.000000
4,4,layer04_candidate_relation_extraction,2482,12159,1076,1406,11083,0.433521,0.088494,0.146984
5,5,layer05_candidate_triple_generation,2482,12159,1076,1406,11083,0.433521,0.088494,0.146984
6,6,layer06_concept_relation_induction,2482,12159,1076,1406,11083,0.433521,0.088494,0.146984
7,7,layer07_hierarchisation,2482,12159,1076,1406,11083,0.433521,0.088494,0.146984
8,8,layer08_axiom_schemata_extraction,2482,12159,1076,1406,11083,0.433521,0.088494,0.146984
9,9,layer09_general_axiom_extraction,2482,12159,1076,1406,11083,0.433521,0.088494,0.146984
10,10,layer10_validation_reasoning,2482,12159,1076,1406,11083,0.433521,0.088494,0.146984
11,11,layer11_inference_completion,2482,12159,1076,1406,11083,0.433521,0.088494,0.146984
12,12,layer12_serialization,2482,12159,1076,1406,11083,0.433521,0.088494,0.146984

## 9. Failures, scheduler state, and saved outputs

In [10]:
failed = pd.DataFrame(batch.get("failed_preview", []))
print("Failed documents:", summary["documents_failed"])
if not failed.empty:
    display(failed[[
        column for column in [
            "selection_index", "document_id", "title", "status",
            "error_type", "error", "run_dir",
        ]
        if column in failed.columns
    ]])

if "scheduler" in batch:
    display(pd.DataFrame([batch["scheduler"]]))

print("Batch output root:", BATCH_ROOT)
print("Selection stream:", BATCH_ROOT / "selection_documents.jsonl")
print("Selection manifest:", BATCH_ROOT / "selection_manifest.json")
print("Progress events:", BATCH_ROOT / "batch_events.jsonl")
print("Aggregate summary:", batch["paths"]["batch_summary"])
print("Per-document CSV:", batch["paths"]["per_document_csv"])
print("Per-relation CSV:", BATCH_ROOT / "aggregate_analysis/per_relation_metrics.csv")
print("Cumulative layer CSV:", BATCH_ROOT / "aggregate_analysis/cumulative_layer_micro_evaluation.csv")
print("Predictions JSONL:", batch["paths"]["predictions_jsonl"])
print("Failures JSONL:", batch["paths"]["failed_documents_jsonl"])

Failed documents: 20

,selection_index,document_id,title,status,error_type,error,run_dir
0,180,DocRED - 41d762b7738a6d38,M. C. Veerabahu Pillai,failed,RuntimeError,No final message.content returned by backend o...,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
1,386,DocRED - d5afb4f79b8f78bf,Economic history of Cambodia,failed,IndexError,list index out of range,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
2,415,DocRED - cf134da0ca9d513b,Vesper sparrow,failed,IndexError,list index out of range,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
3,418,DocRED - f1c3a9b6567acdea,Gromshin Heights,failed,IndexError,list index out of range,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
4,458,DocRED - 2e2db7fa57b135a2,"Afonso, Prince Imperial of Brazil",failed,RuntimeError,layer01_country_aware: response length 29639 e...,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
5,482,DocRED - aeb35b88a907b67f,Ages of consent in Oceania,failed,IndexError,list index out of range,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
6,508,DocRED - 63e458d75bdcdc0b,Jane Livingston,failed,IndexError,list index out of range,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
7,523,DocRED - d496f3bf42d98809,Wayne Gretzky Drive,failed,RuntimeError,No final message.content returned by backend o...,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
8,529,DocRED - 753581dbb1e75a38,Uptoi Village,failed,IndexError,list index out of range,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
9,537,DocRED - 34443841a446b053,Phyllonorycter issikii,failed,IndexError,list index out of range,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
10,567,DocRED - 1a1ae5bd9653f3a2,Scimitar oryx,failed,IndexError,list index out of range,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
11,589,DocRED - 98e4c77830e81d00,"Tire, İzmir",failed,RuntimeError,No final message.content returned by backend o...,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
12,649,DocRED - 96c4fbc14123ac9a,Ramblin' on My Mind,failed,RuntimeError,No final message.content returned by backend o...,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
13,757,DocRED - 41167d3897fd404f,Carl Dix,failed,IndexError,list index out of range,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
14,831,DocRED - 5892bb8f26a1d5c2,Vätsäri Wilderness Area,failed,RuntimeError,No final message.content returned by backend o...,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
15,839,DocRED - db2887e593e5e140,Peters Club,failed,IndexError,list index out of range,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
16,849,DocRED - 090a1f9e7d3030de,First Gallagher Ministry,failed,IndexError,list index out of range,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
17,854,DocRED - ff71412088fdd6fd,"List of islands of Western Australia, M–Q",failed,IndexError,list index out of range,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
18,919,DocRED - 4f132e289eeacc18,Ålgård Line,failed,RuntimeError,No final message.content returned by backend o...,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...
19,945,DocRED - e69e35c93312485e,Bajofondo,failed,IndexError,list index out of range,/home/galencarmedeiro/git/postdoc/NeoOLAF/exam...

,expected_total,documents_prepared,documents_finished,documents_completed_or_resumed,documents_failed,documents_resumed,max_pending_documents,elapsed_seconds
0,998,998,998,978,20,5,4,5791.882

Batch output root: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/runs/docred_native_v5_1_dev_streaming
Selection stream: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/runs/docred_native_v5_1_dev_streaming/selection_documents.jsonl
Selection manifest: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/runs/docred_native_v5_1_dev_streaming/selection_manifest.json
Progress events: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/runs/docred_native_v5_1_dev_streaming/batch_events.jsonl
Aggregate summary: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/runs/docred_native_v5_1_dev_streaming/aggregate_analysis/batch_summary.json
Per-document CSV: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/runs/docred_native_v5_1_dev_streaming/aggregate_analysis/per_document_metrics.csv
Per-relation CSV: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/runs/docred_native_v5_1_dev_streaming/aggregate_analysis/per_relation_metrics.csv
Cumulative layer CSV: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/runs/docred_native_v5_1_dev_streaming/aggregate_analysis/cumulative_layer_micro_evaluation.csv
Predictions JSONL: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/runs/docred_native_v5_1_dev_streaming/aggregate_analysis/predictions.jsonl
Failures JSONL: /home/galencarmedeiro/git/postdoc/NeoOLAF/examples/RAGTreeDatasets/runs/docred_native_v5_1_dev_streaming/aggregate_analysis/failed_documents.jsonl

## 10. Launch the complete dev split

After the five-document dev smoke result is acceptable, change only:

```python
RUN_ALL_DEV_DOCUMENTS = True
```

Rerun the switch/configuration, preflight, and batch cells. Keep the same `BATCH_ROOT`. Completed smoke documents are detected by their scientific fingerprints and skipped.

The full run still reads all 106,924 JSONL lines to locate matching records, but it retains only the current line and at most `DOCUMENT_WORKERS` submitted document jobs. It does **not** create a list of every dev document in RAM.

For sustained HTTP 429 errors, reduce `DOCUMENT_WORKERS` from `4` to `3` before reducing `LAYER_WORKERS`.